<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TblItemsSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        
        $payload = [
                    [
                        'id_item' => 1,
                        'item_code' => 'ALP.001',
                        'item_name' => 'Alpha Pinene',
                        'description' => null,
                        'id_item_category' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 2,
                        'item_code' => 'CIN.001',
                        'item_name' => 'Cineol',
                        'description' => null,
                        'id_item_category' => 2,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 3,
                        'item_code' => 'CSF.001',
                        'item_name' => 'Caustic Soda Flake',
                        'description' => null,
                        'id_item_category' => 3,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 4,
                        'item_code' => 'DNL.001',
                        'item_name' => 'Daun Nilam',
                        'description' => null,
                        'id_item_category' => 4,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 5,
                        'item_code' => 'DPT.001',
                        'item_name' => 'Depentine',
                        'description' => null,
                        'id_item_category' => 5,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 6,
                        'item_code' => 'FAC.001',
                        'item_name' => 'Fumaric Acid Tech Grade',
                        'description' => null,
                        'id_item_category' => 6,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 7,
                        'item_code' => 'IAS.001',
                        'item_name' => 'Pine Oil',
                        'description' => null,
                        'id_item_category' => 7,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 8,
                        'item_code' => 'ICO.001',
                        'item_name' => 'Gum Copal PWS Grade',
                        'description' => null,
                        'id_item_category' => 8,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 9,
                        'item_code' => 'ICO.002',
                        'item_name' => 'Gum Copal DBB Grade',
                        'description' => null,
                        'id_item_category' => 8,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 10,
                        'item_code' => 'ICO.003',
                        'item_name' => 'Gum Copal WS Grade',
                        'description' => null,
                        'id_item_category' => 8,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 11,
                        'item_code' => 'ICO.004',
                        'item_name' => 'Gum Copal Dust',
                        'description' => null,
                        'id_item_category' => 8,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 12,
                        'item_code' => 'ICO.005',
                        'item_name' => 'Gum Copal Asalan Grade',
                        'description' => null,
                        'id_item_category' => 8,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 13,
                        'item_code' => 'ICO.006',
                        'item_name' => 'Gum Copal Debu',
                        'description' => null,
                        'id_item_category' => 8,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 14,
                        'item_code' => 'IDA.001',
                        'item_name' => 'Gum Damar ABX',
                        'description' => null,
                        'id_item_category' => 9,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 15,
                        'item_code' => 'IDA.002',
                        'item_name' => 'Gum Damar CDX',
                        'description' => null,
                        'id_item_category' => 9,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 16,
                        'item_code' => 'IDA.003',
                        'item_name' => 'Gum Damar AB MIX',
                        'description' => null,
                        'id_item_category' => 9,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 17,
                        'item_code' => 'IDB.001',
                        'item_name' => 'DAMAR BATU',
                        'description' => null,
                        'id_item_category' => 10,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 18,
                        'item_code' => 'IDE.001',
                        'item_name' => 'Terpineol',
                        'description' => null,
                        'id_item_category' => 11,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 19,
                        'item_code' => 'IGE.001',
                        'item_name' => 'Oleo Pine Resin',
                        'description' => null,
                        'id_item_category' => 12,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 20,
                        'item_code' => 'IKI.001',
                        'item_name' => 'PARAFFIN YSW 60',
                        'description' => null,
                        'id_item_category' => 13,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 21,
                        'item_code' => 'IKI.002',
                        'item_name' => 'Parafin SRW Fully refined 58',
                        'description' => null,
                        'id_item_category' => 13,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 22,
                        'item_code' => 'IKI.003',
                        'item_name' => 'parafin srw semi refined 58',
                        'description' => null,
                        'id_item_category' => 13,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 23,
                        'item_code' => 'ILB.001',
                        'item_name' => 'Limbah',
                        'description' => null,
                        'id_item_category' => 14,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 24,
                        'item_code' => 'IPA.001',
                        'item_name' => 'Seng Plat Ukuran 025 x 914 x 1829 (S)',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 25,
                        'item_code' => 'IPA.002',
                        'item_name' => 'Seng Plat Ukuran 020 x 762 x 50 m',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 26,
                        'item_code' => 'IPA.003',
                        'item_name' => 'Seng Plat Ukuran 020 x 914 x 1829',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 27,
                        'item_code' => 'IPA.004',
                        'item_name' => 'IBC',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 28,
                        'item_code' => 'IPA.005',
                        'item_name' => 'Drum GR',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 29,
                        'item_code' => 'IPA.006',
                        'item_name' => 'TUTUP ATAS DRUM - BESAR (GR)',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 30,
                        'item_code' => 'IPA.007',
                        'item_name' => 'TUTUP ATAS DRUM - KECIL (GR)',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 31,
                        'item_code' => 'IPA.008',
                        'item_name' => 'TUTUP BAWAH DRUM (GR)',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 32,
                        'item_code' => 'IPA.010',
                        'item_name' => 'Drum Fiber',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 33,
                        'item_code' => 'IPA.011',
                        'item_name' => 'Drum Besi',
                        'description' => null,
                        'id_item_category' => 15,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 34,
                        'item_code' => 'IRO.001',
                        'item_name' => 'Gum Rosin X Grade',
                        'description' => null,
                        'id_item_category' => 16,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 35,
                        'item_code' => 'IRO.002',
                        'item_name' => 'Gum Rosin WW Grade',
                        'description' => null,
                        'id_item_category' => 16,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 36,
                        'item_code' => 'IRO.003',
                        'item_name' => 'Gum Rosin WG',
                        'description' => null,
                        'id_item_category' => 16,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 37,
                        'item_code' => 'IRO.004',
                        'item_name' => 'Gum Rosin Black Grade',
                        'description' => null,
                        'id_item_category' => 16,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 38,
                        'item_code' => 'ITU.001',
                        'item_name' => 'Gum Turpentine',
                        'description' => null,
                        'id_item_category' => 17,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 39,
                        'item_code' => 'ITU.002',
                        'item_name' => 'Gum Turpentine Grade B',
                        'description' => null,
                        'id_item_category' => 17,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 40,
                        'item_code' => 'LHM.001',
                        'item_name' => 'Lithium Hydroxide Monohydrate',
                        'description' => null,
                        'id_item_category' => 18,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 41,
                        'item_code' => 'MEL.001',
                        'item_name' => 'Melamine Powder',
                        'description' => null,
                        'id_item_category' => 19,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 42,
                        'item_code' => 'SAC.001',
                        'item_name' => 'Stearic Acid Type 1801',
                        'description' => null,
                        'id_item_category' => 20,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 43,
                        'item_code' => 'SAC.002',
                        'item_name' => 'Stearic Acid Type 1807',
                        'description' => null,
                        'id_item_category' => 20,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 44,
                        'item_code' => 'SAC.003',
                        'item_name' => 'Stearic Acid Type 1810',
                        'description' => null,
                        'id_item_category' => 20,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 45,
                        'item_code' => 'SAC.004',
                        'item_name' => 'Stearic Acid Type 1838',
                        'description' => null,
                        'id_item_category' => 20,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 46,
                        'item_code' => 'SAC.005',
                        'item_name' => 'Stearic Acid Type 1840',
                        'description' => null,
                        'id_item_category' => 20,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 47,
                        'item_code' => 'SAC.006',
                        'item_name' => 'Stearic Acid Type 1842',
                        'description' => null,
                        'id_item_category' => 20,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 48,
                        'item_code' => 'SOL.001',
                        'item_name' => 'Sereh Oil',
                        'description' => null,
                        'id_item_category' => 21,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 49,
                        'item_code' => 'STP.001',
                        'item_name' => 'Sodium Tripolyphosphate',
                        'description' => null,
                        'id_item_category' => 22,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_item' => 50,
                        'item_code' => 'WOL.001',
                        'item_name' => 'White Oil',
                        'description' => null,
                        'id_item_category' => 23,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
        ];

        $chunks = array_chunk($payload, 50);
        foreach ($chunks as $chunk) {
            DB::table('tbl_items')->insertOrIgnore($chunk);
        }

        Schema::enableForeignKeyConstraints();
    }
}
