<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TblInvoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        $payload = [
                    [
                        'id_invoice' => 1,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 1,
                        'id_vendor' => 1,
                        'id_doc_type' => 1,
                        'id_pr' => 1,
                        'id_norek_vendor' => 1,
                        'nama_bank' => 'Standard Chartered Bank',
                        'nama_penerima' => 'KRISHNA SUKSES ABADI PT',
                        'norek' => '8104041301425849',
                        'truck' => '3123 ff',
                        'invoice_date' => '2025-12-03 00:00:00',
                        'invoice_number' => 'INVOICE.SBB.2512.001',
                        'delivery_date' => '2025-12-27 00:00:00',
                        'file_name' => null,
                        'created_at' => '2025-12-03 09:34:57',
                        'updated_at' => '2025-12-03 18:31:14',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 2,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 1,
                        'id_vendor' => 5,
                        'id_doc_type' => 1,
                        'id_pr' => 2,
                        'id_norek_vendor' => 0,
                        'nama_bank' => '0',
                        'nama_penerima' => '0',
                        'norek' => '0',
                        'truck' => 'fasfas',
                        'invoice_date' => '2025-12-03 00:00:00',
                        'invoice_number' => 'INVOICE.SBB.2512.002',
                        'delivery_date' => null,
                        'file_name' => null,
                        'created_at' => '2025-12-03 11:35:43',
                        'updated_at' => '2025-12-03 11:35:43',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 8,
                        'id_user' => 1,
                        'id_departement' => 1,
                        'id_company' => 1,
                        'id_vendor' => 1,
                        'id_doc_type' => 1,
                        'id_pr' => 2,
                        'id_norek_vendor' => 1,
                        'nama_bank' => 'Standard Chartered Bank',
                        'nama_penerima' => 'KRISHNA SUKSES ABADI PT',
                        'norek' => '8104041301425849',
                        'truck' => 'B 3123 RA',
                        'invoice_date' => '2025-11-23 00:00:00',
                        'invoice_number' => 'INVOICE.SBB.2511.002',
                        'delivery_date' => null,
                        'file_name' => null,
                        'created_at' => '2025-11-23 08:51:03',
                        'updated_at' => '2025-11-23 08:51:50',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 9,
                        'id_user' => 1,
                        'id_departement' => 1,
                        'id_company' => 6,
                        'id_vendor' => 6,
                        'id_doc_type' => 1,
                        'id_pr' => 6,
                        'id_norek_vendor' => 6,
                        'nama_bank' => 'Bank mandiri',
                        'nama_penerima' => 'Fatma Sari',
                        'norek' => '1230007763917',
                        'truck' => 'B 2313 RE',
                        'invoice_date' => '2025-11-21 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2511.001',
                        'delivery_date' => null,
                        'file_name' => null,
                        'created_at' => '2025-11-24 07:20:36',
                        'updated_at' => '2025-11-24 07:20:36',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 10,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 30,
                        'id_doc_type' => 1,
                        'id_pr' => 11,
                        'id_norek_vendor' => 30,
                        'nama_bank' => 'BCA',
                        'nama_penerima' => 'PT.LAVARO CIPTA KREASI',
                        'norek' => '8832100641',
                        'truck' => 'B 2313 RE',
                        'invoice_date' => '2025-11-26 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2511.002',
                        'delivery_date' => null,
                        'file_name' => null,
                        'created_at' => '2025-11-26 09:06:25',
                        'updated_at' => '2025-11-26 09:06:25',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 13,
                        'id_user' => 1,
                        'id_departement' => 1,
                        'id_company' => 1,
                        'id_vendor' => 2,
                        'id_doc_type' => 1,
                        'id_pr' => 14,
                        'id_norek_vendor' => 2,
                        'nama_bank' => 'BANK ACEH',
                        'nama_penerima' => 'ISMAIL MUSE',
                        'norek' => '07302055900466',
                        'truck' => 'dADas',
                        'invoice_date' => '2025-11-28 00:00:00',
                        'invoice_number' => 'INVOICE.SBB.2511.002',
                        'delivery_date' => null,
                        'file_name' => null,
                        'created_at' => '2025-11-28 03:09:25',
                        'updated_at' => '2025-11-28 03:09:25',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 14,
                        'id_user' => 60,
                        'id_departement' => 18,
                        'id_company' => 6,
                        'id_vendor' => 155,
                        'id_doc_type' => 1,
                        'id_pr' => 48,
                        'id_norek_vendor' => 161,
                        'nama_bank' => 'BCA',
                        'nama_penerima' => 'RENDI IRSANDI',
                        'norek' => '8370355755',
                        'truck' => '',
                        'invoice_date' => '2025-12-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2512.003',
                        'delivery_date' => '2025-12-10 00:00:00',
                        'file_name' => '1765364229_97c28efad31987342dc5.jpg',
                        'created_at' => '2025-12-10 10:56:14',
                        'updated_at' => '2025-12-10 10:57:09',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 15,
                        'id_user' => 60,
                        'id_departement' => 18,
                        'id_company' => 6,
                        'id_vendor' => 158,
                        'id_doc_type' => 1,
                        'id_pr' => 51,
                        'id_norek_vendor' => 165,
                        'nama_bank' => 'BCA',
                        'nama_penerima' => 'PT. FREIGHT LINER MEDAN',
                        'norek' => '7850289991',
                        'truck' => '',
                        'invoice_date' => '2025-12-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2512.004',
                        'delivery_date' => '2025-12-10 00:00:00',
                        'file_name' => '1765364297_457d65cefdf2f1d866da.jpg',
                        'created_at' => '2025-12-10 10:57:54',
                        'updated_at' => '2025-12-10 10:58:17',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 16,
                        'id_user' => 25,
                        'id_departement' => 1,
                        'id_company' => 5,
                        'id_vendor' => 1,
                        'id_doc_type' => 1,
                        'id_pr' => 179,
                        'id_norek_vendor' => 1,
                        'nama_bank' => 'Standard Chartered Bank',
                        'nama_penerima' => 'KRISHNA SUKSES ABADI PT',
                        'norek' => '8104041301425849',
                        'truck' => 'czxcxzc',
                        'invoice_date' => '2025-12-19 00:00:00',
                        'invoice_number' => 'INVOICE.NVL.2512.001',
                        'delivery_date' => null,
                        'file_name' => null,
                        'created_at' => '2025-12-19 01:59:52',
                        'updated_at' => '2025-12-19 01:59:52',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 17,
                        'id_user' => 52,
                        'id_departement' => 6,
                        'id_company' => 6,
                        'id_vendor' => 174,
                        'id_doc_type' => 1,
                        'id_pr' => 446,
                        'id_norek_vendor' => 180,
                        'nama_bank' => 'OCBC',
                        'nama_penerima' => 'SIDDHANTH NEELESH MAHESHWARI',
                        'norek' => '020810361822',
                        'truck' => 'FUSO - BM 8564 QN & COLT DIESEL BL 8633 YA',
                        'invoice_date' => '2026-01-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.005',
                        'delivery_date' => '2026-01-10 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-15 06:21:22',
                        'updated_at' => '2026-01-15 06:21:44',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 18,
                        'id_user' => 52,
                        'id_departement' => 6,
                        'id_company' => 6,
                        'id_vendor' => 174,
                        'id_doc_type' => 1,
                        'id_pr' => 448,
                        'id_norek_vendor' => 180,
                        'nama_bank' => 'OCBC',
                        'nama_penerima' => 'SIDDHANTH NEELESH MAHESHWARI',
                        'norek' => '020810361822',
                        'truck' => 'COLT DIESEL - BL 8633 YA',
                        'invoice_date' => '2026-01-15 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.006',
                        'delivery_date' => '2026-01-11 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-15 06:27:24',
                        'updated_at' => '2026-01-15 06:27:24',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 19,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 174,
                        'id_doc_type' => 1,
                        'id_pr' => 472,
                        'id_norek_vendor' => 180,
                        'nama_bank' => 'OCBC',
                        'nama_penerima' => 'SIDDHANTH NEELESH MAHESHWARI',
                        'norek' => '020810361822',
                        'truck' => 'BK 8928 SL & BK 0150 XF ',
                        'invoice_date' => '2026-01-15 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.007',
                        'delivery_date' => '2026-01-15 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-19 07:26:37',
                        'updated_at' => '2026-01-19 07:28:32',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 20,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 473,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8628 ZT ',
                        'invoice_date' => '2026-01-15 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.008',
                        'delivery_date' => '2026-01-15 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-19 07:29:53',
                        'updated_at' => '2026-01-19 07:29:53',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 21,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 495,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8860 GB ',
                        'invoice_date' => '2026-01-17 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.009',
                        'delivery_date' => '2026-01-17 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-20 09:19:45',
                        'updated_at' => '2026-01-20 09:19:45',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 22,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 500,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BK 8159 XF ',
                        'invoice_date' => '2026-01-19 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.010',
                        'delivery_date' => '2026-01-19 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-21 04:19:31',
                        'updated_at' => '2026-01-21 04:19:31',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 23,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 174,
                        'id_doc_type' => 1,
                        'id_pr' => 517,
                        'id_norek_vendor' => 180,
                        'nama_bank' => 'OCBC',
                        'nama_penerima' => 'SIDDHANTH NEELESH MAHESHWARI',
                        'norek' => '020810361822',
                        'truck' => 'BM 8146 SJ ',
                        'invoice_date' => '2026-01-14 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.011',
                        'delivery_date' => '2026-01-14 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-22 06:54:59',
                        'updated_at' => '2026-01-22 06:55:13',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 24,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 174,
                        'id_doc_type' => 1,
                        'id_pr' => 548,
                        'id_norek_vendor' => 180,
                        'nama_bank' => 'OCBC',
                        'nama_penerima' => 'SIDDHANTH NEELESH MAHESHWARI',
                        'norek' => '020810361822',
                        'truck' => 'BK 8928 SL ',
                        'invoice_date' => '2026-01-25 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.012',
                        'delivery_date' => '2026-01-25 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-27 03:45:18',
                        'updated_at' => '2026-01-27 03:45:18',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 25,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 524,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BK 8928 SL ',
                        'invoice_date' => '2026-01-22 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.013',
                        'delivery_date' => '2026-01-22 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-27 03:47:01',
                        'updated_at' => '2026-01-27 03:47:01',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 26,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 591,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BK 8874 YS',
                        'invoice_date' => '2026-01-28 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.014',
                        'delivery_date' => '2026-01-28 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-01-29 07:06:00',
                        'updated_at' => '2026-01-29 07:06:43',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 27,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 611,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL 8367 B ',
                        'invoice_date' => '2026-01-31 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.015',
                        'delivery_date' => '2026-01-31 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-02 07:35:32',
                        'updated_at' => '2026-02-02 07:35:45',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 28,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 631,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8930 KC ',
                        'invoice_date' => '2026-02-01 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.016',
                        'delivery_date' => '2026-02-01 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-03 04:14:34',
                        'updated_at' => '2026-02-03 04:14:34',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 29,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 630,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BK 8928 SL ',
                        'invoice_date' => '2026-02-01 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.017',
                        'delivery_date' => '2026-02-01 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-03 04:16:18',
                        'updated_at' => '2026-02-03 04:16:18',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 30,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 263,
                        'id_doc_type' => 1,
                        'id_pr' => 628,
                        'id_norek_vendor' => 267,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'TASNUDIN ',
                        'norek' => '7299850905',
                        'truck' => 'BG 8653 NQ / BC 8275 UC',
                        'invoice_date' => '2026-02-02 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.018',
                        'delivery_date' => '2026-02-02 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-03 06:34:43',
                        'updated_at' => '2026-02-03 06:34:43',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 31,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 610,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8375 KN',
                        'invoice_date' => '2026-01-30 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2601.019',
                        'delivery_date' => '2026-01-30 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-03 07:10:30',
                        'updated_at' => '2026-02-03 07:10:30',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 32,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 647,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8375 KN ',
                        'invoice_date' => '2026-02-03 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.020',
                        'delivery_date' => '2026-02-03 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-04 08:15:30',
                        'updated_at' => '2026-02-04 08:15:30',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 33,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 679,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8367B',
                        'invoice_date' => '2026-02-04 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.021',
                        'delivery_date' => '2026-02-04 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-05 08:43:01',
                        'updated_at' => '2026-02-05 08:53:59',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 34,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 678,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BK 8928 SL & BM 9027 PB',
                        'invoice_date' => '2026-02-03 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.022',
                        'delivery_date' => '2026-02-03 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-05 08:46:08',
                        'updated_at' => '2026-02-05 08:46:08',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 35,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 683,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F',
                        'invoice_date' => '2026-02-05 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.023',
                        'delivery_date' => '2026-06-05 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-05 08:50:41',
                        'updated_at' => '2026-02-05 08:50:41',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 36,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 722,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BM 9027 PB',
                        'invoice_date' => '2026-02-08 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.024',
                        'delivery_date' => '2026-02-08 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-10 01:46:08',
                        'updated_at' => '2026-02-10 01:46:08',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 37,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 723,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BK 1727 WQ',
                        'invoice_date' => '2026-02-09 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.025',
                        'delivery_date' => '2026-02-09 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-10 01:47:00',
                        'updated_at' => '2026-02-10 01:47:00',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 38,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 716,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL4649F/BL8367B',
                        'invoice_date' => '2026-02-07 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.026',
                        'delivery_date' => '2026-02-07 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-10 04:53:30',
                        'updated_at' => '2026-02-10 04:53:30',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 39,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 259,
                        'id_doc_type' => 1,
                        'id_pr' => 797,
                        'id_norek_vendor' => 262,
                        'nama_bank' => 'BRI',
                        'nama_penerima' => 'RISKON ',
                        'norek' => '108801000821560',
                        'truck' => 'BB8140CA',
                        'invoice_date' => '2026-02-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.027',
                        'delivery_date' => '2026-02-10 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-11 06:17:57',
                        'updated_at' => '2026-02-11 06:17:57',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 40,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 61,
                        'id_doc_type' => 1,
                        'id_pr' => 804,
                        'id_norek_vendor' => 60,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'AKMALA DEWI',
                        'norek' => '1048858283',
                        'truck' => 'BL 8961 Z',
                        'invoice_date' => '2026-02-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.028',
                        'delivery_date' => '2026-02-09 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-12 04:32:58',
                        'updated_at' => '2026-02-12 04:32:58',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 41,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 61,
                        'id_doc_type' => 1,
                        'id_pr' => 803,
                        'id_norek_vendor' => 60,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'AKMALA DEWI',
                        'norek' => '1048858283',
                        'truck' => 'BL 8570 B ',
                        'invoice_date' => '2026-02-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.029',
                        'delivery_date' => '2026-02-10 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-12 04:51:36',
                        'updated_at' => '2026-02-12 04:51:36',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 42,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 802,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'B 9344 TXW',
                        'invoice_date' => '2026-02-09 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.030',
                        'delivery_date' => '2026-02-09 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-12 04:52:33',
                        'updated_at' => '2026-02-12 04:52:33',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 43,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 827,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BK 8928 SL ',
                        'invoice_date' => '2026-02-12 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.031',
                        'delivery_date' => '2026-02-11 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-13 04:34:27',
                        'updated_at' => '2026-02-13 04:34:27',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 44,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 825,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BM 9027 PB ',
                        'invoice_date' => '2026-02-12 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.032',
                        'delivery_date' => '2026-02-11 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-13 04:36:21',
                        'updated_at' => '2026-02-13 04:36:21',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 45,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 822,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8375 KN ',
                        'invoice_date' => '2026-02-09 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.033',
                        'delivery_date' => '2026-02-09 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-13 04:37:43',
                        'updated_at' => '2026-02-13 04:37:43',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 46,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 856,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8960 AG ',
                        'invoice_date' => '2026-02-14 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.034',
                        'delivery_date' => '2026-02-14 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-16 06:42:01',
                        'updated_at' => '2026-02-16 06:42:01',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 47,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 851,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL 8367 B',
                        'invoice_date' => '2026-02-12 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.035',
                        'delivery_date' => '2026-02-12 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-16 07:10:33',
                        'updated_at' => '2026-02-16 07:10:33',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 48,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 853,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL 8649 F ',
                        'invoice_date' => '2026-02-12 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.036',
                        'delivery_date' => '2026-02-12 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-16 07:15:46',
                        'updated_at' => '2026-02-16 07:15:46',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 49,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 867,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F',
                        'invoice_date' => '2026-02-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.037',
                        'delivery_date' => '2026-02-16 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-18 08:45:10',
                        'updated_at' => '2026-02-18 08:45:10',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 50,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 857,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8375 KN ',
                        'invoice_date' => '2026-02-13 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.038',
                        'delivery_date' => '2026-02-13 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-19 02:03:58',
                        'updated_at' => '2026-02-19 02:03:58',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 51,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 306,
                        'id_doc_type' => 1,
                        'id_pr' => 886,
                        'id_norek_vendor' => 312,
                        'nama_bank' => 'BANK MANDIRI ',
                        'nama_penerima' => 'MASRAWANI HARAHAP',
                        'norek' => '1060016599147',
                        'truck' => 'BB8289RC',
                        'invoice_date' => '2026-02-11 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.039',
                        'delivery_date' => '2026-02-12 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-19 06:23:39',
                        'updated_at' => '2026-02-19 06:23:39',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 52,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 61,
                        'id_doc_type' => 1,
                        'id_pr' => 878,
                        'id_norek_vendor' => 60,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'AKMALA DEWI',
                        'norek' => '1048858283',
                        'truck' => 'BL 8961Z & BL 8573 B ',
                        'invoice_date' => '2026-02-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.040',
                        'delivery_date' => '2026-02-16 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-19 08:22:40',
                        'updated_at' => '2026-02-19 08:22:40',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 53,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 308,
                        'id_doc_type' => 1,
                        'id_pr' => 895,
                        'id_norek_vendor' => 314,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'SYAFRI AMIN',
                        'norek' => '7256388825',
                        'truck' => 'BL8559ZE',
                        'invoice_date' => '2026-02-14 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.041',
                        'delivery_date' => '2026-02-14 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-20 04:29:10',
                        'updated_at' => '2026-02-20 04:29:10',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 54,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 913,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8367B/BL8649F',
                        'invoice_date' => '2026-02-20 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.042',
                        'delivery_date' => '2026-02-20 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-24 01:33:57',
                        'updated_at' => '2026-02-24 01:33:57',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 55,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 308,
                        'id_doc_type' => 1,
                        'id_pr' => 926,
                        'id_norek_vendor' => 314,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'SYAFRI AMIN',
                        'norek' => '7256388825',
                        'truck' => 'BK8482GE BK8247EP BL8624LB BL8559ZE',
                        'invoice_date' => '2026-02-23 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.043',
                        'delivery_date' => '2026-02-23 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-24 06:19:55',
                        'updated_at' => '2026-02-24 06:19:55',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 56,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 968,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F',
                        'invoice_date' => '2026-02-23 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.044',
                        'delivery_date' => '2026-02-23 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-27 07:43:58',
                        'updated_at' => '2026-02-27 07:43:58',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 57,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 5,
                        'id_doc_type' => 1,
                        'id_pr' => 972,
                        'id_norek_vendor' => 5,
                        'nama_bank' => 'BANK ACEH',
                        'nama_penerima' => 'WAHYUDI',
                        'norek' => '07302400020193',
                        'truck' => 'BK8955EI BK8735EP BK8438EK',
                        'invoice_date' => '2026-02-18 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.045',
                        'delivery_date' => '2026-02-18 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-27 07:46:55',
                        'updated_at' => '2026-02-27 07:47:15',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 58,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 308,
                        'id_doc_type' => 1,
                        'id_pr' => 974,
                        'id_norek_vendor' => 314,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'SYAFRI AMIN',
                        'norek' => '7256388825',
                        'truck' => 'BL 8559 ZE & BK 8247 EP',
                        'invoice_date' => '2026-02-25 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2602.046',
                        'delivery_date' => '2026-02-25 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-02-27 08:37:31',
                        'updated_at' => '2026-02-27 08:37:31',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 59,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 994,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BK8661RD',
                        'invoice_date' => '2026-03-01 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.047',
                        'delivery_date' => '2026-03-01 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-03 04:36:02',
                        'updated_at' => '2026-03-03 04:36:02',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 60,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 1007,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F',
                        'invoice_date' => '2026-03-02 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.048',
                        'delivery_date' => '2026-03-02 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-04 04:01:19',
                        'updated_at' => '2026-03-06 03:26:18',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 61,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 88,
                        'id_doc_type' => 1,
                        'id_pr' => 1016,
                        'id_norek_vendor' => 87,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Rizky Ariga Setiawan',
                        'norek' => '7169834088',
                        'truck' => 'BL 8525 ZU ',
                        'invoice_date' => '2026-03-03 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.049',
                        'delivery_date' => '2026-03-03 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-04 04:11:57',
                        'updated_at' => '2026-03-04 04:11:57',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 62,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 308,
                        'id_doc_type' => 1,
                        'id_pr' => 1060,
                        'id_norek_vendor' => 0,
                        'nama_bank' => '0',
                        'nama_penerima' => '0',
                        'norek' => '0',
                        'truck' => 'BL8559/BL8570B',
                        'invoice_date' => '2026-03-04 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.050',
                        'delivery_date' => '2026-03-04 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-06 05:36:01',
                        'updated_at' => '2026-03-06 05:36:01',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 63,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 1099,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F BL8367B',
                        'invoice_date' => '2026-03-05 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.051',
                        'delivery_date' => '2026-03-05 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-10 06:36:20',
                        'updated_at' => '2026-03-10 06:36:20',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 64,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 96,
                        'id_doc_type' => 1,
                        'id_pr' => 1065,
                        'id_norek_vendor' => 95,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Syali Indra, S.Sos. I',
                        'norek' => '1050352672',
                        'truck' => 'BL8470JH',
                        'invoice_date' => '2026-03-04 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.052',
                        'delivery_date' => '2026-03-04 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-10 06:50:29',
                        'updated_at' => '2026-03-10 06:50:29',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 65,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 1125,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F',
                        'invoice_date' => '2026-03-11 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.053',
                        'delivery_date' => '2026-03-11 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-12 04:07:11',
                        'updated_at' => '2026-03-12 04:07:11',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 66,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 96,
                        'id_doc_type' => 1,
                        'id_pr' => 1120,
                        'id_norek_vendor' => 95,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Syali Indra, S.Sos. I',
                        'norek' => '1050352672',
                        'truck' => 'BL 8201 B',
                        'invoice_date' => '2026-03-10 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.054',
                        'delivery_date' => '2026-03-10 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-12 05:39:45',
                        'updated_at' => '2026-03-12 05:39:45',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 67,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 96,
                        'id_doc_type' => 1,
                        'id_pr' => 1118,
                        'id_norek_vendor' => 95,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Syali Indra, S.Sos. I',
                        'norek' => '1050352672',
                        'truck' => 'BL 8201 B',
                        'invoice_date' => '2026-03-09 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.055',
                        'delivery_date' => '2026-03-09 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-12 05:40:43',
                        'updated_at' => '2026-03-12 05:40:43',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 68,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 96,
                        'id_doc_type' => 1,
                        'id_pr' => 1152,
                        'id_norek_vendor' => 95,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Syali Indra, S.Sos. I',
                        'norek' => '1050352672',
                        'truck' => 'BL 8201 B',
                        'invoice_date' => '2026-03-12 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.056',
                        'delivery_date' => '2026-02-12 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-13 10:14:55',
                        'updated_at' => '2026-03-13 10:14:55',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 69,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 81,
                        'id_doc_type' => 1,
                        'id_pr' => 1172,
                        'id_norek_vendor' => 354,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'NASIRUDIN',
                        'norek' => '1057562486',
                        'truck' => 'BL 8462 PG, BL 8316 CO, BL 8316 VO',
                        'invoice_date' => '2026-03-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.057',
                        'delivery_date' => '2026-03-13 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-16 06:05:59',
                        'updated_at' => '2026-03-16 06:05:59',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 70,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 1169,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL 8649F',
                        'invoice_date' => '2026-03-13 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.058',
                        'delivery_date' => '2026-03-13 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-16 06:14:25',
                        'updated_at' => '2026-03-16 06:14:25',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 71,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 1170,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BL8649F/BK9750BFD',
                        'invoice_date' => '2026-03-14 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.059',
                        'delivery_date' => '2026-03-14 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-16 06:17:56',
                        'updated_at' => '2026-03-16 06:17:56',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 72,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 81,
                        'id_doc_type' => 1,
                        'id_pr' => 1171,
                        'id_norek_vendor' => 354,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'NASIRUDIN',
                        'norek' => '1057562486',
                        'truck' => 'BL 8316 VO',
                        'invoice_date' => '2026-03-12 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.060',
                        'delivery_date' => '2026-03-12 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-16 06:32:03',
                        'updated_at' => '2026-03-16 06:32:03',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 73,
                        'id_user' => 40,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 78,
                        'id_doc_type' => 1,
                        'id_pr' => 1174,
                        'id_norek_vendor' => 355,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Muhtada Hairy',
                        'norek' => '7302112872',
                        'truck' => 'BL 8627 GB',
                        'invoice_date' => '2026-03-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.061',
                        'delivery_date' => '2026-03-14 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-16 06:49:38',
                        'updated_at' => '2026-03-16 06:49:38',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 74,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 96,
                        'id_doc_type' => 1,
                        'id_pr' => 1178,
                        'id_norek_vendor' => 95,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Syali Indra, S.Sos. I',
                        'norek' => '1050352672',
                        'truck' => 'BL 6201 B, BL 8376 B, BL 8470 JM',
                        'invoice_date' => '2026-03-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.062',
                        'delivery_date' => '2026-03-15 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-17 04:50:40',
                        'updated_at' => '2026-03-17 04:50:40',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 75,
                        'id_user' => 50,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 268,
                        'id_doc_type' => 1,
                        'id_pr' => 1183,
                        'id_norek_vendor' => 272,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'KARI',
                        'norek' => '7257605838',
                        'truck' => 'BK 9750 BED / BL 8649 F',
                        'invoice_date' => '2026-03-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.063',
                        'delivery_date' => '2026-03-16 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-17 05:05:31',
                        'updated_at' => '2026-03-17 05:05:45',
                        'deleted_at' => null,
                    ],
                    [
                        'id_invoice' => 76,
                        'id_user' => 41,
                        'id_departement' => 8,
                        'id_company' => 6,
                        'id_vendor' => 96,
                        'id_doc_type' => 1,
                        'id_pr' => 1198,
                        'id_norek_vendor' => 95,
                        'nama_bank' => 'BSI',
                        'nama_penerima' => 'Syali Indra, S.Sos. I',
                        'norek' => '1050352672',
                        'truck' => 'BL 8201 B',
                        'invoice_date' => '2026-03-16 00:00:00',
                        'invoice_number' => 'INVOICE.KSA.2603.064',
                        'delivery_date' => '2026-03-16 00:00:00',
                        'file_name' => null,
                        'created_at' => '2026-03-18 05:39:03',
                        'updated_at' => '2026-03-18 05:39:03',
                        'deleted_at' => null,
                    ],
        ];

        // Break payload into manageable memory chunks and insert
        $chunks = array_chunk($payload, 50);
        foreach ($chunks as $chunk) {
            DB::table('tbl_invoice')->insertOrIgnore($chunk);
        }

        Schema::enableForeignKeyConstraints();
    }
}