<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblIkbSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tbl_ikb')->truncate();

        $data = [
            [
                'id_ikb' => 2,
                'id_user' => 39,
                'sales' => 22,
                'id_warehouse' => 5,
                'id_vendor' => 354,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 2,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2603.002',
                'po_number' => 'I-PO/MOL FTY/0226_1231',
                'so_number' => 'SO.KSA.2602.00015',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => '(MANGALAM) NHAVA SHEVA, INDIA',
                'qr' => null,
                'status' => 0,
                'booking_date' => '2026-04-17 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-03-29 22:13:14',
                'updated_at' => '2026-04-08 17:51:49',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 4,
                'id_user' => 33,
                'sales' => 33,
                'id_warehouse' => 5,
                'id_vendor' => 262,
                'id_departement' => 17,
                'id_company' => 1,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 2,
                'ikb_number' => 'IKB.SBB.GA.2603.002',
                'po_number' => '4100002991',
                'so_number' => 'SO.SBB.2603.00015',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'JOMBANG JAWA TIMUR',
                'qr' => null,
                'status' => 12,
                'booking_date' => '2026-04-10 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-03-30 17:38:29',
                'updated_at' => '2026-03-31 02:27:46',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 5,
                'id_user' => 33,
                'sales' => 33,
                'id_warehouse' => 5,
                'id_vendor' => 262,
                'id_departement' => 17,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 3,
                'ikb_number' => 'IKB.KSA.GA.2603.003',
                'po_number' => '4100002992',
                'so_number' => 'SO.KSA.2603.00035',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'JOMBANG JAWA TIMUR',
                'qr' => null,
                'status' => 12,
                'booking_date' => '2026-04-10 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-03-30 17:44:18',
                'updated_at' => '2026-03-31 02:26:10',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 6,
                'id_user' => 40,
                'sales' => 21,
                'id_warehouse' => 5,
                'id_vendor' => 345,
                'id_departement' => 8,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 1,
                'ikb_number' => 'IKB.KSA.PURCHASING.2603.001',
                'po_number' => '4500097478',
                'so_number' => 'SO.KSA.2602.00009',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'NIPSEA PURWAKARTA',
                'qr' => null,
                'status' => 10,
                'booking_date' => '2026-04-01 00:00:00',
                'stuffing_date' => '2026-04-01 00:00:00',
                'delivery_date' => '2026-04-01 00:00:00',
                'created_at' => '2026-03-30 18:44:42',
                'updated_at' => '2026-04-01 20:35:57',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 7,
                'id_user' => 39,
                'sales' => 24,
                'id_warehouse' => 5,
                'id_vendor' => 348,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 3,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2603.003',
                'po_number' => '47823469',
                'so_number' => 'SO.KSA.2603.00024',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'SERANG, BANTEN',
                'qr' => null,
                'status' => 10,
                'booking_date' => '2026-04-01 00:00:00',
                'stuffing_date' => '2026-04-04 00:00:00',
                'delivery_date' => '2026-04-04 00:00:00',
                'created_at' => '2026-03-30 20:50:43',
                'updated_at' => '2026-04-08 18:29:13',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 8,
                'id_user' => 39,
                'sales' => 22,
                'id_warehouse' => 5,
                'id_vendor' => 349,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 4,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2603.004',
                'po_number' => '',
                'so_number' => 'SO.KSA.2603.00033',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'NHAVA SHEVA, INDIA',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-01 00:00:00',
                'stuffing_date' => '2026-04-08 00:00:00',
                'delivery_date' => null,
                'created_at' => '2026-03-30 21:10:16',
                'updated_at' => '2026-04-08 06:34:47',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 9,
                'id_user' => 39,
                'sales' => 22,
                'id_warehouse' => 10,
                'id_vendor' => 354,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 5,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2603.005',
                'po_number' => 'I-PO/MOL FTY/0326_1256',
                'so_number' => 'SO.KSA.2602.00015',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => '(MANGALAM), NHAVA SHEVA, INDIA',
                'qr' => null,
                'status' => 8,
                'booking_date' => '2026-03-31 00:00:00',
                'stuffing_date' => '2026-04-04 00:00:00',
                'delivery_date' => null,
                'created_at' => '2026-03-30 21:28:33',
                'updated_at' => '2026-04-08 02:48:07',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 12,
                'id_user' => 69,
                'sales' => 69,
                'id_warehouse' => 5,
                'id_vendor' => 351,
                'id_departement' => 3,
                'id_company' => 1,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 3,
                'ikb_number' => 'IKB.SBB.PA.2603.003',
                'po_number' => '4100002991',
                'so_number' => 'PO.SBB.2603.00015',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'JOMBANG JAWA TIMUR',
                'qr' => null,
                'status' => 5,
                'booking_date' => '2026-04-10 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-03-31 00:17:26',
                'updated_at' => '2026-03-31 18:09:39',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 14,
                'id_user' => 69,
                'sales' => 69,
                'id_warehouse' => 16,
                'id_vendor' => 350,
                'id_departement' => 3,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 4,
                'ikb_number' => 'IKB.KSA.PA.2603.004',
                'po_number' => 'HI260210-1',
                'so_number' => 'SO.KSA.2602.00012',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'BUSAN, KOREA',
                'qr' => null,
                'status' => 8,
                'booking_date' => '2026-03-31 00:00:00',
                'stuffing_date' => '2026-03-31 00:00:00',
                'delivery_date' => '2026-03-31 00:00:00',
                'created_at' => '2026-03-31 02:38:08',
                'updated_at' => '2026-04-07 21:23:23',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 15,
                'id_user' => 69,
                'sales' => 69,
                'id_warehouse' => 5,
                'id_vendor' => 351,
                'id_departement' => 3,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 5,
                'ikb_number' => 'IKB.KSA.PA.2604.005',
                'po_number' => '4100002992',
                'so_number' => 'SO.KSA.2603.00035',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'JOMBANG, JAWA TIMUR',
                'qr' => null,
                'status' => 5,
                'booking_date' => '2026-04-10 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-03-31 18:05:01',
                'updated_at' => '2026-04-01 20:05:17',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 16,
                'id_user' => 1,
                'sales' => 66,
                'id_warehouse' => 5,
                'id_vendor' => 2,
                'id_departement' => 1,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 4,
                'number' => 1,
                'ikb_number' => 'IKB.KSA.IT.2604.001',
                'po_number' => '',
                'so_number' => '',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'Testing',
                'qr' => null,
                'status' => 0,
                'booking_date' => '2026-04-01 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-03-31 21:08:32',
                'updated_at' => '2026-03-31 21:08:32',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 17,
                'id_user' => 40,
                'sales' => 20,
                'id_warehouse' => 5,
                'id_vendor' => 357,
                'id_departement' => 8,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 2,
                'ikb_number' => 'IKB.KSA.PURCHASING.2604.002',
                'po_number' => '',
                'so_number' => 'SO.KSA.2604.00037',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'GUDANG BATANG ',
                'qr' => null,
                'status' => 10,
                'booking_date' => '2026-04-02 00:00:00',
                'stuffing_date' => '2026-04-02 00:00:00',
                'delivery_date' => '2026-04-02 00:00:00',
                'created_at' => '2026-04-01 19:46:39',
                'updated_at' => '2026-04-01 23:06:41',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 18,
                'id_user' => 40,
                'sales' => 21,
                'id_warehouse' => 5,
                'id_vendor' => 345,
                'id_departement' => 8,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 3,
                'ikb_number' => 'IKB.SBB.PURCHASING.2604.003',
                'po_number' => '4500099716 ',
                'so_number' => 'SO.KSA.2604.00043',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'NIPSEA JAKARTA ',
                'qr' => null,
                'status' => 0,
                'booking_date' => '2026-04-14 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-01 21:09:20',
                'updated_at' => '2026-04-06 00:56:50',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 19,
                'id_user' => 39,
                'sales' => 20,
                'id_warehouse' => 10,
                'id_vendor' => 358,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 6,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2604.006',
                'po_number' => '26XYC0004',
                'so_number' => 'SO.SBB.2603.00010',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'MAFANG, CHINA',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-06 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-02 00:55:13',
                'updated_at' => '2026-04-08 18:22:43',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 20,
                'id_user' => 39,
                'sales' => 24,
                'id_warehouse' => 5,
                'id_vendor' => 365,
                'id_departement' => 9,
                'id_company' => 1,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 7,
                'ikb_number' => 'IKB.SBB.LOGISTIC.2604.007',
                'po_number' => 'WSP20260301',
                'so_number' => 'SO.SBB.2510.00056',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'WUZHOU, CHINA',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-07 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-02 01:50:46',
                'updated_at' => '2026-04-08 18:20:28',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 21,
                'id_user' => 39,
                'sales' => 24,
                'id_warehouse' => 21,
                'id_vendor' => 360,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 8,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2604.008',
                'po_number' => 'RF26PKS07',
                'so_number' => 'SO.KSA.2512.00198',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'MAFANG, CHINA',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-08 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-02 02:14:05',
                'updated_at' => '2026-04-08 18:24:58',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 22,
                'id_user' => 39,
                'sales' => 20,
                'id_warehouse' => 21,
                'id_vendor' => 361,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 9,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2604.009',
                'po_number' => '',
                'so_number' => 'SC.KSA.2603.00026',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'CHATTOGRAM, BANGLADESH',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-08 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-02 02:19:24',
                'updated_at' => '2026-04-08 18:23:54',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 23,
                'id_user' => 52,
                'sales' => 52,
                'id_warehouse' => 5,
                'id_vendor' => 42,
                'id_departement' => 6,
                'id_company' => 1,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 6,
                'number' => 1,
                'ikb_number' => 'IKB.SBB.PRODUCTION.2604.001',
                'po_number' => '',
                'so_number' => '',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'CV. LAFAZA PEKALONGAN',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-04 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-05 19:09:57',
                'updated_at' => '2026-04-08 18:24:28',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 24,
                'id_user' => 40,
                'sales' => 20,
                'id_warehouse' => 5,
                'id_vendor' => 357,
                'id_departement' => 8,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 4,
                'ikb_number' => 'IKB.KSA.PURCHASING.2604.004',
                'po_number' => '',
                'so_number' => 'SO.KSA.2604.00039',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'GUDANG BATANG ',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-04 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-05 20:54:06',
                'updated_at' => '2026-04-08 18:23:04',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 25,
                'id_user' => 40,
                'sales' => 20,
                'id_warehouse' => 5,
                'id_vendor' => 357,
                'id_departement' => 8,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 5,
                'ikb_number' => 'IKB.KSA.PURCHASING.2604.005',
                'po_number' => '',
                'so_number' => 'SO.KSA.2604.00042',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'GUDANG BATANG ',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-06 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-05 21:17:37',
                'updated_at' => '2026-04-08 18:21:47',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 26,
                'id_user' => 51,
                'sales' => 51,
                'id_warehouse' => 5,
                'id_vendor' => 359,
                'id_departement' => 13,
                'id_company' => 1,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 1,
                'ikb_number' => 'IKB.SBB.MARKETING.2604.001',
                'po_number' => ' SC.SBB.0403.00001   ',
                'so_number' => 'SO.SBB.2603.00010',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'CHINA',
                'qr' => null,
                'status' => 10,
                'booking_date' => '2026-04-07 00:00:00',
                'stuffing_date' => '2026-04-07 00:00:00',
                'delivery_date' => '2026-04-07 00:00:00',
                'created_at' => '2026-04-07 00:06:35',
                'updated_at' => '2026-04-08 17:53:13',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 28,
                'id_user' => 39,
                'sales' => 20,
                'id_warehouse' => 5,
                'id_vendor' => 354,
                'id_departement' => 9,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 1,
                'number' => 10,
                'ikb_number' => 'IKB.KSA.LOGISTIC.2604.010',
                'po_number' => '',
                'so_number' => 'SO.KSA.2609.00029 (PI 032)',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'FUJIAN NANPING (XIAMEN, CHINA)',
                'qr' => null,
                'status' => 6,
                'booking_date' => '2026-04-10 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-07 00:49:55',
                'updated_at' => '2026-04-08 18:21:33',
                'deleted_at' => null
            ],
            [
                'id_ikb' => 29,
                'id_user' => 69,
                'sales' => 69,
                'id_warehouse' => 5,
                'id_vendor' => 377,
                'id_departement' => 3,
                'id_company' => 6,
                'id_doc_type' => 4,
                'id_ikb_transaction_type' => 5,
                'number' => 6,
                'ikb_number' => 'IKB.KSA.PA.2604.006',
                'po_number' => 'TERPENIOL ',
                'so_number' => '',
                'ri_number' => '',
                'sk_number' => '',
                'do_number' => '',
                'batch_number' => '',
                'destination' => 'GRESIK JAWA TIMUR',
                'qr' => null,
                'status' => 3,
                'booking_date' => '2026-04-09 00:00:00',
                'stuffing_date' => null,
                'delivery_date' => null,
                'created_at' => '2026-04-07 21:25:23',
                'updated_at' => '2026-04-07 23:32:31',
                'deleted_at' => null
            ]
        ];

        // Insert in chunks to avoid packet-size limits
        foreach (array_chunk($data, 500) as $chunk) {
            DB::table('tbl_ikb')->insert($chunk);
        }
    }
}
