<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tbl_permissions')->truncate();

        $data = [
            [
                'id_permission' => 1,
                'permission_name' => 'company.view',
                'permission_description' => 'View Company List',
                'module' => 'Company',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 2,
                'permission_name' => 'company.create',
                'permission_description' => 'Create Company',
                'module' => 'Company',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 3,
                'permission_name' => 'company.edit',
                'permission_description' => 'Edit Company',
                'module' => 'Company',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 4,
                'permission_name' => 'company.delete',
                'permission_description' => 'Delete Company',
                'module' => 'Company',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 5,
                'permission_name' => 'branch.view',
                'permission_description' => 'View Branch List',
                'module' => 'Branch',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 6,
                'permission_name' => 'branch.create',
                'permission_description' => 'Create Branch',
                'module' => 'Branch',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 7,
                'permission_name' => 'branch.edit',
                'permission_description' => 'Edit Branch',
                'module' => 'Branch',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 8,
                'permission_name' => 'branch.delete',
                'permission_description' => 'Delete Branch',
                'module' => 'Branch',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 9,
                'permission_name' => 'dept.view',
                'permission_description' => 'View Department List',
                'module' => 'Department',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 10,
                'permission_name' => 'dept.create',
                'permission_description' => 'Create Department',
                'module' => 'Department',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 11,
                'permission_name' => 'dept.edit',
                'permission_description' => 'Edit Department',
                'module' => 'Department',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 12,
                'permission_name' => 'dept.delete',
                'permission_description' => 'Delete Department',
                'module' => 'Department',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 13,
                'permission_name' => 'vendor.view',
                'permission_description' => 'View Vendor List',
                'module' => 'Vendor',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 14,
                'permission_name' => 'vendor.create',
                'permission_description' => 'Create Vendor',
                'module' => 'Vendor',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 15,
                'permission_name' => 'vendor.edit',
                'permission_description' => 'Edit Vendor',
                'module' => 'Vendor',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 16,
                'permission_name' => 'vendor.delete',
                'permission_description' => 'Delete Vendor',
                'module' => 'Vendor',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 17,
                'permission_name' => 'vendor.upload',
                'permission_description' => 'Upload Vendor',
                'module' => 'Vendor',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 18,
                'permission_name' => 'vendor.download',
                'permission_description' => 'Download Vendor',
                'module' => 'Vendor',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 19,
                'permission_name' => 'uom.view',
                'permission_description' => 'View UOM List',
                'module' => 'UOM',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 20,
                'permission_name' => 'uom.create',
                'permission_description' => 'Create UOM',
                'module' => 'UOM',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 21,
                'permission_name' => 'uom.edit',
                'permission_description' => 'Edit UOM',
                'module' => 'UOM',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 22,
                'permission_name' => 'uom.delete',
                'permission_description' => 'Delete UOM',
                'module' => 'UOM',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 23,
                'permission_name' => 'package.view',
                'permission_description' => 'View Package List',
                'module' => 'Package',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 24,
                'permission_name' => 'package.create',
                'permission_description' => 'Create Package',
                'module' => 'Package',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 25,
                'permission_name' => 'package.edit',
                'permission_description' => 'Edit Package',
                'module' => 'Package',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 26,
                'permission_name' => 'package.delete',
                'permission_description' => 'Delete Package',
                'module' => 'Package',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 27,
                'permission_name' => 'cost_type.view',
                'permission_description' => 'View Cost Type List',
                'module' => 'Cost Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 28,
                'permission_name' => 'cost_type.create',
                'permission_description' => 'Create Cost Type',
                'module' => 'Cost Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 29,
                'permission_name' => 'cost_type.edit',
                'permission_description' => 'Edit Cost Type',
                'module' => 'Cost Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 30,
                'permission_name' => 'cost_type.delete',
                'permission_description' => 'Delete Cost Type',
                'module' => 'Cost Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 31,
                'permission_name' => 'cost.view',
                'permission_description' => 'View Cost List',
                'module' => 'Cost',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 32,
                'permission_name' => 'cost.create',
                'permission_description' => 'Create Cost',
                'module' => 'Cost',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 33,
                'permission_name' => 'cost.edit',
                'permission_description' => 'Edit Cost',
                'module' => 'Cost',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 34,
                'permission_name' => 'cost.delete',
                'permission_description' => 'Delete Cost',
                'module' => 'Cost',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 35,
                'permission_name' => 'currency.view',
                'permission_description' => 'View Currency List',
                'module' => 'Currency',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 36,
                'permission_name' => 'currency.create',
                'permission_description' => 'Create Currency',
                'module' => 'Currency',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 37,
                'permission_name' => 'currency.edit',
                'permission_description' => 'Edit Currency',
                'module' => 'Currency',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 38,
                'permission_name' => 'currency.delete',
                'permission_description' => 'Delete Currency',
                'module' => 'Currency',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 39,
                'permission_name' => 'attachment.view',
                'permission_description' => 'View Attachment List',
                'module' => 'Attachment',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 40,
                'permission_name' => 'attachment.create',
                'permission_description' => 'Create Attachment',
                'module' => 'Attachment',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 41,
                'permission_name' => 'attachment.edit',
                'permission_description' => 'Edit Attachment',
                'module' => 'Attachment',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 42,
                'permission_name' => 'attachment.delete',
                'permission_description' => 'Delete Attachment',
                'module' => 'Attachment',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 43,
                'permission_name' => 'loan.view',
                'permission_description' => 'View Loan List',
                'module' => 'Loan',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 44,
                'permission_name' => 'loan.create',
                'permission_description' => 'Create Loan',
                'module' => 'Loan',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 45,
                'permission_name' => 'loan.edit',
                'permission_description' => 'Edit Loan',
                'module' => 'Loan',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 46,
                'permission_name' => 'loan.delete',
                'permission_description' => 'Delete Loan',
                'module' => 'Loan',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 47,
                'permission_name' => 'tax_type.view',
                'permission_description' => 'View Tax Type List',
                'module' => 'Tax Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 48,
                'permission_name' => 'tax_type.create',
                'permission_description' => 'Create Tax Type',
                'module' => 'Tax Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 49,
                'permission_name' => 'tax_type.edit',
                'permission_description' => 'Edit Tax Type',
                'module' => 'Tax Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 50,
                'permission_name' => 'tax_type.delete',
                'permission_description' => 'Delete Tax Type',
                'module' => 'Tax Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 51,
                'permission_name' => 'tax.view',
                'permission_description' => 'View Tax List',
                'module' => 'Tax',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 52,
                'permission_name' => 'tax.create',
                'permission_description' => 'Create Tax',
                'module' => 'Tax',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 53,
                'permission_name' => 'tax.edit',
                'permission_description' => 'Edit Tax',
                'module' => 'Tax',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 54,
                'permission_name' => 'tax.delete',
                'permission_description' => 'Delete Tax',
                'module' => 'Tax',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 55,
                'permission_name' => 'position.view',
                'permission_description' => 'View Position List',
                'module' => 'Position',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 56,
                'permission_name' => 'position.create',
                'permission_description' => 'Create Position',
                'module' => 'Position',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 57,
                'permission_name' => 'position.edit',
                'permission_description' => 'Edit Position',
                'module' => 'Position',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 58,
                'permission_name' => 'position.delete',
                'permission_description' => 'Delete Position',
                'module' => 'Position',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 59,
                'permission_name' => 'item_category.view',
                'permission_description' => 'View Item Category List',
                'module' => 'Item Category',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 60,
                'permission_name' => 'item_category.create',
                'permission_description' => 'Create Item Category',
                'module' => 'Item Category',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 61,
                'permission_name' => 'item_category.edit',
                'permission_description' => 'Edit Item Category',
                'module' => 'Item Category',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 62,
                'permission_name' => 'item_category.delete',
                'permission_description' => 'Delete Item Category',
                'module' => 'Item Category',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 63,
                'permission_name' => 'item.view',
                'permission_description' => 'View Item List',
                'module' => 'Item',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-24 22:53:59',
            ],
            [
                'id_permission' => 66,
                'permission_name' => 'item.create',
                'permission_description' => 'Create Item',
                'module' => 'Item',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 67,
                'permission_name' => 'item.edit',
                'permission_description' => 'Edit Item',
                'module' => 'Item',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 68,
                'permission_name' => 'item.delete',
                'permission_description' => 'Delete Item',
                'module' => 'Item',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 69,
                'permission_name' => 'doc_type.view',
                'permission_description' => 'View Document Type List',
                'module' => 'Document Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 70,
                'permission_name' => 'doc_type.create',
                'permission_description' => 'Create Document Type',
                'module' => 'Document Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 71,
                'permission_name' => 'doc_type.edit',
                'permission_description' => 'Edit Document Type',
                'module' => 'Document Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 72,
                'permission_name' => 'doc_type.delete',
                'permission_description' => 'Delete Document Type',
                'module' => 'Document Type',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 73,
                'permission_name' => 'dashboard.view',
                'permission_description' => 'View Dashboard',
                'module' => 'Dashboard',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 74,
                'permission_name' => 'dashboard.view.dept',
                'permission_description' => 'View Dept Dashboard',
                'module' => 'Dashboard',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 75,
                'permission_name' => 'dashboard.view.subordinate',
                'permission_description' => 'View User Dashboard',
                'module' => 'Dashboard',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 76,
                'permission_name' => 'pr.view.all',
                'permission_description' => 'View PR List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 77,
                'permission_name' => 'pr.view.dept',
                'permission_description' => 'View PR Dept List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 78,
                'permission_name' => 'pr.view.subordinate',
                'permission_description' => 'View PR Subordinate List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 79,
                'permission_name' => 'pr.create',
                'permission_description' => 'Create New PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 80,
                'permission_name' => 'pr.edit',
                'permission_description' => 'Edit Draft PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 81,
                'permission_name' => 'pr.delete',
                'permission_description' => 'Delete Draft PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 82,
                'permission_name' => 'pr.print',
                'permission_description' => 'Print PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 83,
                'permission_name' => 'pr_detail.view',
                'permission_description' => 'View PR Detail List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 84,
                'permission_name' => 'pr_detail.create',
                'permission_description' => 'Create New PR Detail',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 85,
                'permission_name' => 'pr_detail.edit',
                'permission_description' => 'Edit Draft PR Detail',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 86,
                'permission_name' => 'pr_detail.delete',
                'permission_description' => 'Delete Draft PR Detail',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 87,
                'permission_name' => 'pr_detail.print',
                'permission_description' => 'Print PR Detail',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 88,
                'permission_name' => 'pr_detail.download',
                'permission_description' => 'Download PR Detail',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 89,
                'permission_name' => 'pr_attachment.view',
                'permission_description' => 'View PR Attachment List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 90,
                'permission_name' => 'pr_attachment.create',
                'permission_description' => 'Create New PR Attachment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 91,
                'permission_name' => 'pr_attachment.edit',
                'permission_description' => 'Edit Draft PR Attachment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 92,
                'permission_name' => 'pr_attachment.delete',
                'permission_description' => 'Delete Draft PR Attachment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 93,
                'permission_name' => 'pr_attachment.download',
                'permission_description' => 'Download PR Attachment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 94,
                'permission_name' => 'pr_payment.view',
                'permission_description' => 'View PR Payment List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 95,
                'permission_name' => 'pr_payment.create',
                'permission_description' => 'Create New PR Payment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 96,
                'permission_name' => 'pr_payment.edit',
                'permission_description' => 'Edit Draft PR Payment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 97,
                'permission_name' => 'pr_payment.delete',
                'permission_description' => 'Delete Draft PR Payment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 98,
                'permission_name' => 'pr_payment.print',
                'permission_description' => 'Print PR Payment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 99,
                'permission_name' => 'pr_payment.download',
                'permission_description' => 'Download PR Payment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 100,
                'permission_name' => 'pr_payment.approve.step1',
                'permission_description' => 'Approve PR Payment (SPV/Manager)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 101,
                'permission_name' => 'pr_payment.cancel_approve.step1',
                'permission_description' => 'Cancel Approve PR Payment (SPV/Manager)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 102,
                'permission_name' => 'pr_payment.approve.step2',
                'permission_description' => 'Approve PR Payment (Director)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 103,
                'permission_name' => 'pr_payment.cancel_approve.step2',
                'permission_description' => 'Cancel Approve PR Payment (Director)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 104,
                'permission_name' => 'pr_payment.revision',
                'permission_description' => 'Revision PR Payment',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 105,
                'permission_name' => 'pr_invoice.view',
                'permission_description' => 'View PR Invoice List',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 106,
                'permission_name' => 'pr_invoice.create',
                'permission_description' => 'Create New PR Invoice',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 107,
                'permission_name' => 'pr_invoice.edit',
                'permission_description' => 'Edit Draft PR Invoice',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 108,
                'permission_name' => 'pr_invoice.delete',
                'permission_description' => 'Delete Draft PR Invoice',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 109,
                'permission_name' => 'pr_invoice.print',
                'permission_description' => 'Print PR Invoice',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 110,
                'permission_name' => 'pr_invoice.download',
                'permission_description' => 'Download PR Invoice',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 111,
                'permission_name' => 'pr.submit',
                'permission_description' => 'Submit PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 112,
                'permission_name' => 'pr.cancel_submit',
                'permission_description' => 'Cancel Submit PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 113,
                'permission_name' => 'pr.approve.step1',
                'permission_description' => 'Approve PR Step 1 (SPV/Manager)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 114,
                'permission_name' => 'pr.cancel_approve.step1',
                'permission_description' => 'Cancel Approve PR Step 1 (SPV/Manager)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 115,
                'permission_name' => 'pr.approve.step2',
                'permission_description' => 'Approve PR Step 2 (Director)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 116,
                'permission_name' => 'pr.cancel_approve.step2',
                'permission_description' => 'Cancel Approve PR Step 2 (Director)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 117,
                'permission_name' => 'pr.approve.step3',
                'permission_description' => 'Approve PR Step 3 (Accounting)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 118,
                'permission_name' => 'pr.cancel_approve.step3',
                'permission_description' => 'Cancel Approve PR Step 3 (Accounting)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 119,
                'permission_name' => 'pr.approve.step4',
                'permission_description' => 'Approve PR Step 4 (Finance Staff)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 120,
                'permission_name' => 'pr.cancel_approve.step4',
                'permission_description' => 'Cancel Approve PR Step 4 (Finance Staff)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 121,
                'permission_name' => 'pr.approve.step5',
                'permission_description' => 'Approve PR Step 5 (Finance SPV)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 122,
                'permission_name' => 'pr.cancel_approve.step5',
                'permission_description' => 'Cancel Approve PR Step 5 (Finance SPV)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 123,
                'permission_name' => 'pr.approve.step6',
                'permission_description' => 'Approve PR Step 6 (CFO)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 124,
                'permission_name' => 'pr.cancel_approve.step6',
                'permission_description' => 'Cancel Approve PR Step 6 (CFO)',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 125,
                'permission_name' => 'pr.reject',
                'permission_description' => 'Reject PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 126,
                'permission_name' => 'pr.revision',
                'permission_description' => 'Revision PR',
                'module' => 'PR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 127,
                'permission_name' => 'sr.view.all',
                'permission_description' => 'View SR List',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 128,
                'permission_name' => 'sr.view.dept',
                'permission_description' => 'View SR Dept List',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 129,
                'permission_name' => 'sr.view.subordinate',
                'permission_description' => 'View SR Subordinate List',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 130,
                'permission_name' => 'sr.create',
                'permission_description' => 'Create New SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 131,
                'permission_name' => 'sr.edit',
                'permission_description' => 'Edit Draft SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 132,
                'permission_name' => 'sr.delete',
                'permission_description' => 'Delete Draft SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 133,
                'permission_name' => 'sr.print',
                'permission_description' => 'Print SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 134,
                'permission_name' => 'sr.download',
                'permission_description' => 'Download SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 135,
                'permission_name' => 'sr_detail.view',
                'permission_description' => 'View SR Detail List',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 136,
                'permission_name' => 'sr_detail.create',
                'permission_description' => 'Create New SR Detail',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 137,
                'permission_name' => 'sr_detail.edit',
                'permission_description' => 'Edit Draft SR Detail',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 138,
                'permission_name' => 'sr_detail.delete',
                'permission_description' => 'Delete Draft SR Detail',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 139,
                'permission_name' => 'sr_detail.print',
                'permission_description' => 'Print SR Detail',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 140,
                'permission_name' => 'sr_detail.download',
                'permission_description' => 'Download SR Detail',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 141,
                'permission_name' => 'sr_attachment.view',
                'permission_description' => 'View SR Attachment List',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 142,
                'permission_name' => 'sr_attachment.create',
                'permission_description' => 'Create New SR Attachment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 143,
                'permission_name' => 'sr_attachment.edit',
                'permission_description' => 'Edit Draft SR Attachment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 144,
                'permission_name' => 'sr_attachment.delete',
                'permission_description' => 'Delete Draft SR Attachment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 145,
                'permission_name' => 'sr_attachment.download',
                'permission_description' => 'Download SR Attachment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 146,
                'permission_name' => 'sr_payment.view',
                'permission_description' => 'View SR Payment List',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 147,
                'permission_name' => 'sr_payment.create',
                'permission_description' => 'Create New SR Payment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 148,
                'permission_name' => 'sr_payment.edit',
                'permission_description' => 'Edit Draft SR Payment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 149,
                'permission_name' => 'sr_payment.delete',
                'permission_description' => 'Delete Draft SR Payment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 150,
                'permission_name' => 'sr_payment.print',
                'permission_description' => 'Print SR Payment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 151,
                'permission_name' => 'sr_payment.download',
                'permission_description' => 'Download SR Payment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 152,
                'permission_name' => 'sr_payment.approve.step1',
                'permission_description' => 'Approve SR Payment (SPV/Manager)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 153,
                'permission_name' => 'sr_payment.cancel_approve.step1',
                'permission_description' => 'Cancel Approve SR Payment (SPV/Manager)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 154,
                'permission_name' => 'sr_payment.approve.step2',
                'permission_description' => 'Approve SR Payment (Director)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 155,
                'permission_name' => 'sr_payment.cancel_approve.step2',
                'permission_description' => 'Cancel Approve SR Payment (Director)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 156,
                'permission_name' => 'sr_payment.revision',
                'permission_description' => 'Revision SR Payment',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 157,
                'permission_name' => 'sr.submit',
                'permission_description' => 'Submit SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 158,
                'permission_name' => 'sr.cancel_submit',
                'permission_description' => 'Cancel Submit SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 159,
                'permission_name' => 'sr.approve.step1',
                'permission_description' => 'Approve SR Step 1 (SPV/Manager)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 160,
                'permission_name' => 'sr.cancel_approve.step1',
                'permission_description' => 'Cancel Approve SR Step 1 (SPV/Manager)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 161,
                'permission_name' => 'sr.approve.step2',
                'permission_description' => 'Approve SR Step 2 (Director)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 162,
                'permission_name' => 'sr.cancel_approve.step2',
                'permission_description' => 'Cancel Approve SR Step 2 (Director)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 163,
                'permission_name' => 'sr.approve.step3',
                'permission_description' => 'Approve SR Step 3 (Accounting)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 164,
                'permission_name' => 'sr.cancel_approve.step3',
                'permission_description' => 'Cancel Approve SR Step 3 (Accounting)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 165,
                'permission_name' => 'sr.approve.step4',
                'permission_description' => 'Approve SR Step 4 (Finance Staff)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 166,
                'permission_name' => 'sr.cancel_approve.step4',
                'permission_description' => 'Cancel Approve SR Step 4 (Finance Staff)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 167,
                'permission_name' => 'sr.approve.step5',
                'permission_description' => 'Approve SR Step 5 (Finance SPV)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 168,
                'permission_name' => 'sr.cancel_approve.step5',
                'permission_description' => 'Cancel Approve SR Step 5 (Finance SPV)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 169,
                'permission_name' => 'sr.approve.step6',
                'permission_description' => 'Approve SR Step 6 (CFO)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 170,
                'permission_name' => 'sr.cancel_approve.step6',
                'permission_description' => 'Cancel Approve SR Step 6 (CFO)',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 171,
                'permission_name' => 'sr.reject',
                'permission_description' => 'Reject SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 172,
                'permission_name' => 'sr.revision',
                'permission_description' => 'Revision SR',
                'module' => 'SR',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 173,
                'permission_name' => 'item_transaction.view.all',
                'permission_description' => 'View Item Transaction All List',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 174,
                'permission_name' => 'item_transaction.view.warehouse',
                'permission_description' => 'View Item Transaction Warehouse List',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 177,
                'permission_name' => 'item_transaction.create',
                'permission_description' => 'Create New Item Transaction',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 178,
                'permission_name' => 'item_transaction.edit',
                'permission_description' => 'Edit Draft Item Transaction',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 179,
                'permission_name' => 'item_transaction.delete',
                'permission_description' => 'Delete Draft Item Transaction',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 180,
                'permission_name' => 'warehouse.view',
                'permission_description' => 'View Warehouse List',
                'module' => 'Warehouse',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 181,
                'permission_name' => 'warehouse.create',
                'permission_description' => 'Create Warehouse',
                'module' => 'Warehouse',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 182,
                'permission_name' => 'warehouse.edit',
                'permission_description' => 'Edit Warehouse',
                'module' => 'Warehouse',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 183,
                'permission_name' => 'warehouse.delete',
                'permission_description' => 'Delete Warehouse',
                'module' => 'Warehouse',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 184,
                'permission_name' => 'ikb.view.all',
                'permission_description' => 'View IKB List',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 185,
                'permission_name' => 'ikb.view.dept',
                'permission_description' => 'View IKB Dept List',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 186,
                'permission_name' => 'ikb.view.warehouse',
                'permission_description' => 'View IKB Warehouse List',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 187,
                'permission_name' => 'ikb.view.subordinate',
                'permission_description' => 'View IKB Subordinate List',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 188,
                'permission_name' => 'ikb.create',
                'permission_description' => 'Create New IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 189,
                'permission_name' => 'ikb.edit',
                'permission_description' => 'Edit Draft IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 190,
                'permission_name' => 'ikb.delete',
                'permission_description' => 'Delete Draft IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 191,
                'permission_name' => 'ikb.print',
                'permission_description' => 'Print IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 192,
                'permission_name' => 'ikb.download',
                'permission_description' => 'Download IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 193,
                'permission_name' => 'ikb_detail.view',
                'permission_description' => 'View IKB Detail List',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 194,
                'permission_name' => 'ikb_detail.create',
                'permission_description' => 'Create New IKB Detail',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 195,
                'permission_name' => 'ikb_detail.edit',
                'permission_description' => 'Edit Draft IKB Detail',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 196,
                'permission_name' => 'ikb_detail.delete',
                'permission_description' => 'Delete Draft IKB Detail',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 197,
                'permission_name' => 'ikb_detail.print',
                'permission_description' => 'Print IKB Detail',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 198,
                'permission_name' => 'ikb_detail.download',
                'permission_description' => 'Download IKB Detail',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 199,
                'permission_name' => 'ikb.submit',
                'permission_description' => 'Submit IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 200,
                'permission_name' => 'ikb.cancel_submit',
                'permission_description' => 'Cancel Submit IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 201,
                'permission_name' => 'ikb.approve.step1',
                'permission_description' => 'Approve IKB Step 1 (SPV/Manager)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 202,
                'permission_name' => 'ikb.cancel_approve.step1',
                'permission_description' => 'Cancel Approve IKB Step 1',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:49',
            ],
            [
                'id_permission' => 203,
                'permission_name' => 'ikb.approve.step2',
                'permission_description' => 'Approve IKB Step 2 (Director Log)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 204,
                'permission_name' => 'ikb.cancel_approve.step2',
                'permission_description' => 'Cancel Approve IKB Step 2',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 205,
                'permission_name' => 'ikb.approve.step3',
                'permission_description' => 'Approve IKB Step 3 (PPIC)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 206,
                'permission_name' => 'ikb.cancel_approve.step3',
                'permission_description' => 'Cancel Approve IKB Step 3',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 207,
                'permission_name' => 'ikb.approve.step4',
                'permission_description' => 'Approve IKB Step 4 (Inventory Control)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 208,
                'permission_name' => 'ikb.cancel_approve.step4',
                'permission_description' => 'Cancel Approve IKB Step 4',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 209,
                'permission_name' => 'ikb.approve.step5',
                'permission_description' => 'Approve IKB Step 5 (Logistic Coord)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 210,
                'permission_name' => 'ikb.cancel_approve.step5',
                'permission_description' => 'Cancel Approve IKB Step 5',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 211,
                'permission_name' => 'ikb.approve.step6',
                'permission_description' => 'Approve IKB Step 6 (Warehouse Staff)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 212,
                'permission_name' => 'ikb.cancel_approve.step6',
                'permission_description' => 'Cancel Approve IKB Step 6',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 213,
                'permission_name' => 'ikb.approve.step7',
                'permission_description' => 'Approve IKB Step 7 (Warehouse SPV)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 214,
                'permission_name' => 'ikb.cancel_approve.step7',
                'permission_description' => 'Cancel Approve IKB Step 7',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 215,
                'permission_name' => 'ikb.approve.step8',
                'permission_description' => 'Approve IKB Step 8 (Security Officer)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 216,
                'permission_name' => 'ikb.cancel_approve.step8',
                'permission_description' => 'Cancel Approve IKB Step 8',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 217,
                'permission_name' => 'ikb.approve.step9',
                'permission_description' => 'Approve IKB Step 9 (Logistic Coord Final)',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 218,
                'permission_name' => 'ikb.cancel_approve.step9',
                'permission_description' => 'Cancel Approve IKB Step 9',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-03-11 02:52:50',
            ],
            [
                'id_permission' => 219,
                'permission_name' => 'ikb.reject',
                'permission_description' => 'Reject IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 220,
                'permission_name' => 'ikb.revision',
                'permission_description' => 'Revision IKB',
                'module' => 'IKB',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 221,
                'permission_name' => 'user.view.all',
                'permission_description' => 'View User List',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 222,
                'permission_name' => 'user.view.dept',
                'permission_description' => 'View User Dept List',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 223,
                'permission_name' => 'user.view.subordinate',
                'permission_description' => 'View User Subordinate List',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 224,
                'permission_name' => 'user.create',
                'permission_description' => 'Create User',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 225,
                'permission_name' => 'user.edit',
                'permission_description' => 'Edit User',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 226,
                'permission_name' => 'user.delete',
                'permission_description' => 'Delete User',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 227,
                'permission_name' => 'user.reset_password',
                'permission_description' => 'Reset Password User',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 228,
                'permission_name' => 'user.change_password',
                'permission_description' => 'Change Password User',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 229,
                'permission_name' => 'user.permissions',
                'permission_description' => 'Manage User Permissions',
                'module' => 'User',
                'created_at' => '2026-02-22 09:56:55',
                'updated_at' => '2026-02-22 09:56:55',
            ],
            [
                'id_permission' => 230,
                'permission_name' => 'vendor.activate',
                'permission_description' => 'Aktivasi Vendor',
                'module' => 'Vendor',
                'created_at' => '2026-02-24 20:32:45',
                'updated_at' => '2026-02-24 20:32:45',
            ],
            [
                'id_permission' => 231,
                'permission_name' => 'attachment.download',
                'permission_description' => 'Download List Attachment',
                'module' => 'Attachment',
                'created_at' => '2026-02-24 22:08:16',
                'updated_at' => '2026-02-24 22:08:16',
            ],
            [
                'id_permission' => 232,
                'permission_name' => 'attachment.upload',
                'permission_description' => 'Import List Attachment',
                'module' => 'Attachment',
                'created_at' => '2026-02-24 22:09:01',
                'updated_at' => '2026-02-24 22:09:01',
            ],
            [
                'id_permission' => 233,
                'permission_name' => 'item_category.download',
                'permission_description' => 'Download Category Item',
                'module' => 'Item Category',
                'created_at' => '2026-02-24 22:50:08',
                'updated_at' => '2026-02-24 22:50:08',
            ],
            [
                'id_permission' => 234,
                'permission_name' => 'item_category.upload',
                'permission_description' => 'Import List Item Category',
                'module' => 'Item Category',
                'created_at' => '2026-02-24 22:50:44',
                'updated_at' => '2026-02-24 22:50:44',
            ],
            [
                'id_permission' => 235,
                'permission_name' => 'item.download',
                'permission_description' => 'Download List Item',
                'module' => 'Item',
                'created_at' => '2026-02-24 22:54:24',
                'updated_at' => '2026-02-24 22:54:24',
            ],
            [
                'id_permission' => 236,
                'permission_name' => 'item.upload',
                'permission_description' => 'Import List Item',
                'module' => 'Item',
                'created_at' => '2026-02-24 22:54:47',
                'updated_at' => '2026-02-24 22:54:47',
            ],
            [
                'id_permission' => 237,
                'permission_name' => 'item_transaction.edit.all',
                'permission_description' => 'Bypass Edit',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-25 06:59:04',
                'updated_at' => '2026-02-25 06:59:04',
            ],
            [
                'id_permission' => 239,
                'permission_name' => 'item_transaction.delete.all',
                'permission_description' => 'Bypass Delete',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-25 07:37:01',
                'updated_at' => '2026-02-25 07:37:01',
            ],
            [
                'id_permission' => 240,
                'permission_name' => 'item_transaction.download',
                'permission_description' => 'Eksport Transaction',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-25 07:37:44',
                'updated_at' => '2026-02-25 07:37:44',
            ],
            [
                'id_permission' => 241,
                'permission_name' => 'item_transaction.upload',
                'permission_description' => 'Import Transaction',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-25 07:38:19',
                'updated_at' => '2026-02-25 07:38:19',
            ],
            [
                'id_permission' => 242,
                'permission_name' => 'item_transaction.out',
                'permission_description' => 'Bypass Outcome',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-25 08:00:59',
                'updated_at' => '2026-02-25 08:00:59',
            ],
            [
                'id_permission' => 243,
                'permission_name' => 'item_transaction.view.report',
                'permission_description' => 'Report Data',
                'module' => 'Item Transaction',
                'created_at' => '2026-02-25 10:50:08',
                'updated_at' => '2026-02-25 10:50:08',
            ],
            [
                'id_permission' => 244,
                'permission_name' => 'item_transaction.detail',
                'permission_description' => 'Detail Item Trasaction',
                'module' => 'Item Transaction',
                'created_at' => '2026-03-12 03:15:27',
                'updated_at' => '2026-03-12 04:42:25',
            ],
            [
                'id_permission' => 245,
                'permission_name' => 'item_transaction.view.subordinate',
                'permission_description' => 'View Item Transaction Subordinate List',
                'module' => 'Item Transaction',
                'created_at' => '2026-03-12 04:46:19',
                'updated_at' => '2026-03-12 04:47:00',
            ],
            [
                'id_permission' => 246,
                'permission_name' => 'ikb.view.attachment',
                'permission_description' => 'View Attachment',
                'module' => 'IKB',
                'created_at' => '2026-03-12 08:42:12',
                'updated_at' => '2026-03-12 08:42:12',
            ],
            [
                'id_permission' => 247,
                'permission_name' => 'contract.view.all',
                'permission_description' => 'View All Contract',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:19:07',
                'updated_at' => '2026-03-17 11:19:07',
            ],
            [
                'id_permission' => 248,
                'permission_name' => 'contract.view.departement',
                'permission_description' => 'View Contract Departement',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:19:50',
                'updated_at' => '2026-03-17 11:19:50',
            ],
            [
                'id_permission' => 249,
                'permission_name' => 'contract.view.subordinate',
                'permission_description' => 'View Contract User',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:21:33',
                'updated_at' => '2026-03-17 11:21:33',
            ],
            [
                'id_permission' => 250,
                'permission_name' => 'contract.create',
                'permission_description' => 'Create Contract',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:22:10',
                'updated_at' => '2026-03-17 11:22:10',
            ],
            [
                'id_permission' => 251,
                'permission_name' => 'contract.edit',
                'permission_description' => 'Edit Contract',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:22:39',
                'updated_at' => '2026-03-17 11:22:39',
            ],
            [
                'id_permission' => 252,
                'permission_name' => 'contract.delete',
                'permission_description' => 'Delete Contract',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:23:13',
                'updated_at' => '2026-03-17 11:23:13',
            ],
            [
                'id_permission' => 253,
                'permission_name' => 'contract.upload',
                'permission_description' => 'Upload Contract Document',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:24:04',
                'updated_at' => '2026-03-17 11:24:04',
            ],
            [
                'id_permission' => 254,
                'permission_name' => 'contract.download',
                'permission_description' => 'Download Contract',
                'module' => 'Contract',
                'created_at' => '2026-03-17 11:26:12',
                'updated_at' => '2026-03-17 11:26:12',
            ],

            // Production Permission
            // ── Production ────────────────────────────────────────────────
            [
                'id_permission' => 255,
                'permission_name' => 'production.view.own',
                'permission_description' => 'View Own Production',
                'module' => 'Production',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id_permission' => 256,
                'permission_name' => 'production.view.all',
                'permission_description' => 'View All Production',
                'module' => 'Production',
                'created_at' => '2026-04-07 15:32:00',
                'updated_at' => '2026-04-07 15:32:00',
            ],
            [
                'id_permission' => 257,
                'permission_name' => 'production.view.dept',
                'permission_description' => 'View Department Production',
                'module' => 'Production',
                'created_at' => '2026-04-07 15:32:00',
                'updated_at' => '2026-04-07 15:32:00',
            ],
            [
                'id_permission' => 258,
                'permission_name' => 'production.view.warehouse',
                'permission_description' => 'View Warehouse Production',
                'module' => 'Production',
                'created_at' => '2026-04-07 15:32:00',
                'updated_at' => '2026-04-07 15:32:00',
            ],
            [
                'id_permission' => 259,
                'permission_name' => 'production.view.detail',
                'permission_description' => 'View Production Detail',
                'module' => 'Production',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id_permission' => 260,
                'permission_name' => 'production.create',
                'permission_description' => 'Create Production',
                'module' => 'Production',
                'created_at' => '2026-04-07 15:32:00',
                'updated_at' => '2026-04-07 15:32:00',
            ],
            [
                'id_permission' => 261,
                'permission_name' => 'production.edit',
                'permission_description' => 'Edit Own Draft Production',
                'module' => 'Production',
                'created_at' => '2026-04-07 15:32:00',
                'updated_at' => '2026-04-07 15:32:00',
            ],
            [
                'id_permission' => 262,
                'permission_name' => 'production.edit.all',
                'permission_description' => 'Edit All Production Drafts',
                'module' => 'Production',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id_permission' => 263,
                'permission_name' => 'production.delete',
                'permission_description' => 'Delete Own Draft Production',
                'module' => 'Production',
                'created_at' => '2026-04-07 15:32:00',
                'updated_at' => '2026-04-07 15:32:00',
            ],
            [
                'id_permission' => 264,
                'permission_name' => 'production.delete.all',
                'permission_description' => 'Delete All Production Drafts',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 265,
                'permission_name' => 'production.submit',
                'permission_description' => 'Submit Production (Draft to Submit)',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 266,
                'permission_name' => 'production.cancel_approve.step1',
                'permission_description' => 'Cancel Submit (Back to Draft)',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 267,
                'permission_name' => 'production.approve.step2',
                'permission_description' => 'Process Production (Approve Step 2)',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 268,
                'permission_name' => 'production.cancel_approve.step2',
                'permission_description' => 'Cancel Process (Back to Submit)',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 269,
                'permission_name' => 'production.approve.step3',
                'permission_description' => 'Verify Production (Approve Step 3)',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 270,
                'permission_name' => 'production.cancel_approve.step3',
                'permission_description' => 'Cancel Verify (Back to Process)',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 271,
                'permission_name' => 'production_material.create',
                'permission_description' => 'Add Material to Production',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 272,
                'permission_name' => 'production_material.edit',
                'permission_description' => 'Edit Material in Production',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 273,
                'permission_name' => 'production_material.delete',
                'permission_description' => 'Delete Material from Production',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 274,
                'permission_name' => 'production_result.create',
                'permission_description' => 'Add Result to Production',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 275,
                'permission_name' => 'production_result.edit',
                'permission_description' => 'Edit Result in Production',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 276,
                'permission_name' => 'production_result.delete',
                'permission_description' => 'Delete Result from Production',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 277,
                'permission_name' => 'production.view.attachment',
                'permission_description' => 'View Production Attachments',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 278,
                'permission_name' => 'production_attachment.create',
                'permission_description' => 'Upload Production Attachment',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 279,
                'permission_name' => 'production_attachment.edit',
                'permission_description' => 'Edit Production Attachment',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 280,
                'permission_name' => 'production_attachment.delete',
                'permission_description' => 'Delete Production Attachment',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 281,
                'permission_name' => 'production.print',
                'permission_description' => 'Print Production Document',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
            [
                'id_permission' => 282,
                'permission_name' => 'production.download',
                'permission_description' => 'Download Production Document',
                'module' => 'Production',
                'created_at' => '2026-04-08 03:12:00',
                'updated_at' => '2026-04-08 03:12:00',
            ],
        ];

        // Insert in chunks to avoid packet-size limits
        foreach (array_chunk($data, 500) as $chunk) {
            DB::table('tbl_permissions')->insert($chunk);
        }
    }
}
