<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblUserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tbl_user')->truncate();

        $data = [
            [
                'id_user' => 1,
                'id_employee' => 'SBB-0000',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 1,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 25,
                'name' => 'Admin',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 1,
                'password' => '$2y$10$0HSVSIn1aRN5hMOIVsX0aOUG2Y.5BHSqNnk8flrDIZNHRxw0qrJ9e',
                'photo' => '1763629652_f29695475c65767f348c.png',
                'phone' => '6282199005570',
                'is_active' => 1,
                'created_at' => '2025-05-02 23:37:30',
                'updated_at' => '2025-12-22 11:42:25',
                'deleted_at' => null
            ],
            [
                'id_user' => 20,
                'id_employee' => 'KSA-0106',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 10,
                'id_position' => 1,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'NEELESH RAMESHCHANDRA MAHESHWARI',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$gpFCK2O7ag3gPDuwJrtDOuHcEWOM2zVH0KG37CTK.BanP.79NYV76',
                'photo' => 'default.jpg',
                'phone' => '628159385142\\n',
                'is_active' => 1,
                'created_at' => '2025-11-19 19:02:06',
                'updated_at' => '2026-03-30 18:56:07',
                'deleted_at' => null
            ],
            [
                'id_user' => 21,
                'id_employee' => 'KSA-0002',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 10,
                'id_position' => 1,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'SIDDHANTH NEELESH MAHESHWARI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$64IIIAw2iBz4KzWQaLJiQ.mShVi1uOlgtuBJIGJBaXlMlzmC8PBIW',
                'photo' => 'default.jpg',
                'phone' => '6287881500280\\n',
                'is_active' => 1,
                'created_at' => '2025-11-19 19:04:37',
                'updated_at' => '2025-12-09 00:17:18',
                'deleted_at' => null
            ],
            [
                'id_user' => 22,
                'id_employee' => 'KSA-0001',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 10,
                'id_position' => 1,
                'id_warehouse' => null,
                'supervisor' => 22,
                'name' => 'VISHAL R MAHESHWARI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$oqysQJx9//uJ/Jl/dwbQnuDwqepNfvgrF6ZBSJ0utkMbw98yuca4a',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 19:05:31',
                'updated_at' => '2025-12-09 11:22:41',
                'deleted_at' => null
            ],
            [
                'id_user' => 23,
                'id_employee' => 'KSA-0004',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 1,
                'id_position' => 6,
                'id_warehouse' => null,
                'supervisor' => 22,
                'name' => 'AMAN SANJAY BHARDWAJ',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$hlLHM5P1YKnItuvEscUiJu6fD21p1fXWKAhiS4NwSQcfdzT7aqsOa',
                'photo' => 'default.jpg',
                'phone' => '6285967264034',
                'is_active' => 1,
                'created_at' => '2025-11-19 19:19:14',
                'updated_at' => '2025-12-21 16:29:32',
                'deleted_at' => null
            ],
            [
                'id_user' => 24,
                'id_employee' => 'KSA-0017',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 8,
                'id_position' => 6,
                'id_warehouse' => null,
                'supervisor' => 22,
                'name' => 'PARASH PRITANDAS JATIANI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$ikX0pbC93rozCxYfxu4rt.85fJASGsi3VFDd.h2pEosjASrsuudq6',
                'photo' => 'default.jpg',
                'phone' => '6282197195968',
                'is_active' => 1,
                'created_at' => '2025-11-19 19:22:12',
                'updated_at' => '2025-12-22 11:59:38',
                'deleted_at' => null
            ],
            [
                'id_user' => 25,
                'id_employee' => 'SBB-0050',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 1,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 23,
                'name' => 'Muh Ibrahim Al Fath',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$NCoxtMHsjbEj8Ix/PXGb6.ZaJIrtOSPSkzBad/zGECg423iUW9rkW',
                'photo' => 'default.jpg',
                'phone' => '6282199005570',
                'is_active' => 1,
                'created_at' => '2025-11-19 19:26:01',
                'updated_at' => '2025-12-20 07:41:48',
                'deleted_at' => null
            ],
            [
                'id_user' => 26,
                'id_employee' => 'KSA-0005',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 7,
                'id_position' => 8,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'CERIA PERTIWI',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$fIrwUpSeYz3GAYyZPsu7rudMEBb/e0InBgm3ZmilUYsjbslazXcG2',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 0,
                'created_at' => '2025-11-19 19:43:50',
                'updated_at' => '2026-03-27 00:40:57',
                'deleted_at' => null
            ],
            [
                'id_user' => 27,
                'id_employee' => 'KSA-0019',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 9,
                'id_position' => 6,
                'id_warehouse' => null,
                'supervisor' => 22,
                'name' => 'SANTY',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$cibyWI2OUNuRRgOYX3HFC.2aqIcmsbTr.hUw.tXATDapWyjIaYFuC',
                'photo' => 'default.jpg',
                'phone' => '6281318889589',
                'is_active' => 1,
                'created_at' => '2025-11-19 19:46:08',
                'updated_at' => '2026-01-20 13:30:16',
                'deleted_at' => null
            ],
            [
                'id_user' => 29,
                'id_employee' => 'KSA-0045',
                'id_company' => 6,
                'id_branch' => 3,
                'id_departement' => 11,
                'id_position' => 2,
                'id_warehouse' => 5,
                'supervisor' => 40,
                'name' => 'KHUSWATUN KHASANAH',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$OXrFTuDNABYUO.G585HVjOVX4gGQDy7w1Cc/kqvEUan66R0Z4sGiS',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 21:15:49',
                'updated_at' => '2026-03-24 20:17:09',
                'deleted_at' => null
            ],
            [
                'id_user' => 30,
                'id_employee' => 'KSA-0089',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 5,
                'id_position' => 6,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'ZULKIFLI, SH. MH',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$dA3.HiUpifFJxdo7W6xESed/9/59KAuUNFyEcZcnAn62Br4ff/Og2',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 22:08:12',
                'updated_at' => '2026-01-05 12:11:08',
                'deleted_at' => null
            ],
            [
                'id_user' => 31,
                'id_employee' => 'SBB-0002',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 6,
                'id_position' => 6,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'KAMIJA',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$zF1k1L7AILBX8Z6usJTOluLSGAk/8p7G0BeeotVUwoNjnlqhOwqa2',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 22:09:57',
                'updated_at' => '2025-11-19 22:09:57',
                'deleted_at' => null
            ],
            [
                'id_user' => 32,
                'id_employee' => 'SBB-0065',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 2,
                'id_position' => 7,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'Sofyan Helmi Purba',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$D374dnSJ73SEgAzQ4REQ0.n1nRZ6xmMVACl8shHrRrt3XuP4XsNbm',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 0,
                'created_at' => '2025-11-19 22:12:34',
                'updated_at' => '2026-03-24 20:19:01',
                'deleted_at' => null
            ],
            [
                'id_user' => 33,
                'id_employee' => 'KSA-0112',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 17,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'DEVITA SIANAWATI 1',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$pUDZkVMGTWAEBUbvuXrwouOSdQJ1BcQ3wnMRktcWSA8VKz6uBBLi2',
                'photo' => 'default.jpg',
                'phone' => '6281231654888',
                'is_active' => 1,
                'created_at' => '2025-11-19 22:19:18',
                'updated_at' => '2026-03-31 00:12:09',
                'deleted_at' => null
            ],
            [
                'id_user' => 34,
                'id_employee' => 'SBB-0041',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 17,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'SUPARDI',
                'nik' => 'Si9hSk1FTFJtcHR0TlJCTkI4VmFmSzhKY2NyR1BzbEYrL3RiYnYrUTVWQT0=',
                'npwp' => 'VUxuWU9rT04wejVyNldCekRRN2FPQT09',
                'level' => 2,
                'password' => '$2y$12$n5IjgT0bpbpA28AoRCFBiu1SMenJobfFCXTbBCgzn9ec5Nb9NazFi',
                'photo' => 'default.jpg',
                'phone' => '6281360355799',
                'is_active' => 1,
                'created_at' => '2025-11-19 22:21:50',
                'updated_at' => '2026-03-25 19:20:26',
                'deleted_at' => null
            ],
            [
                'id_user' => 35,
                'id_employee' => 'SBB-0064',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 14,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'Inggrid Febby Isnaini Sutarlan',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$YM1vzdVfVVPqXPb0sUjGlOy/5SvvYNmkg8JtWAbjcx10aJSlCYYs2',
                'photo' => 'default.jpg',
                'phone' => '6289678910546',
                'is_active' => 1,
                'created_at' => '2025-11-19 22:32:48',
                'updated_at' => '2025-12-22 12:54:55',
                'deleted_at' => null
            ],
            [
                'id_user' => 36,
                'id_employee' => 'KSA-0067',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 12,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'SRI HATIN',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$IL67bmJGKZMViWO6hx3eYu7g856B11Ajj/iBSjWQjIwiurV9Mtd3a',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 0,
                'created_at' => '2025-11-19 22:35:45',
                'updated_at' => '2026-03-27 00:41:36',
                'deleted_at' => null
            ],
            [
                'id_user' => 37,
                'id_employee' => 'KSA-0015',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 9,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 27,
                'name' => 'NENG NURHAYATI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$SjYzdhaoENpeBeV0zMqelOZLPED7K5qyj5Pvf0RLqDvK159DbYNIW',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 22:40:15',
                'updated_at' => '2025-11-19 22:40:15',
                'deleted_at' => null
            ],
            [
                'id_user' => 38,
                'id_employee' => 'SBB-0004',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 9,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 27,
                'name' => 'NURAINI TRIHASTUTI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$12$41QFrEv.99CLFuZK4aN8w.GadDgzlvH7ik2/0HaatmFXibzJ5EGyO',
                'photo' => 'default.jpg',
                'phone' => '6281329632332',
                'is_active' => 1,
                'created_at' => '2025-11-19 22:43:09',
                'updated_at' => '2026-03-24 20:28:14',
                'deleted_at' => null
            ],
            [
                'id_user' => 39,
                'id_employee' => 'SBB-0021',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 9,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 24,
                'name' => 'Titin Isri Yanni',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$ZKGGVFkLc8kwbanq5KIPduHo6qxbWrxW/oHOK/kReVZ8RG3Ze6jAm',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 22:45:29',
                'updated_at' => '2025-12-30 13:26:28',
                'deleted_at' => null
            ],
            [
                'id_user' => 40,
                'id_employee' => 'KSA-0020',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 8,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 24,
                'name' => 'ZARQA NURKHALISHAH HAMDANI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$FGhP6G08yGkzttTBMyz3leXLMhQHaeXlC/jMa8fRj4ZMirE2vYuFW',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 22:48:07',
                'updated_at' => '2025-11-19 22:48:07',
                'deleted_at' => null
            ],
            [
                'id_user' => 41,
                'id_employee' => 'KSA-0010',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 8,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 24,
                'name' => 'KHUSNAWATI (NANA)',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$R6Rg0hhGmXZR4UF7ttaiyug.g.bLE7SE4ZDEZOhozUzWWEWfVcxp.',
                'photo' => 'default.jpg',
                'phone' => '6282211571832',
                'is_active' => 1,
                'created_at' => '2025-11-19 22:51:15',
                'updated_at' => '2026-01-06 16:11:54',
                'deleted_at' => null
            ],
            [
                'id_user' => 42,
                'id_employee' => 'KSA-0018',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 5,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 30,
                'name' => 'ROY GITA SAPUTRA',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$dd2kt69Hs2w.DnTjkgUNfuwTwPYkjJ1gUSa7S/G1KfJ1DGbtn65uC',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 0,
                'created_at' => '2025-11-19 22:55:41',
                'updated_at' => '2026-03-27 00:42:14',
                'deleted_at' => null
            ],
            [
                'id_user' => 43,
                'id_employee' => 'KSA-0029',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 6,
                'id_position' => 8,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'ANDI HARIANTO SITOHANG',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$MF/FhZftIg9CcV7bTrjLuuN37gtUY6pBS1HRvoc7dUv2/a4DX3s2.',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 23:35:55',
                'updated_at' => '2025-11-19 23:35:55',
                'deleted_at' => null
            ],
            [
                'id_user' => 44,
                'id_employee' => 'SBB-0070',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 2,
                'id_position' => 6,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'FITRI INDRIYANI',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$MhNMhLuYcW5aqgwb3jfHxuDG.9uMCdfl1h8Rhdz7rg11nZPz.900i',
                'photo' => 'default.jpg',
                'phone' => '6289699844788',
                'is_active' => 1,
                'created_at' => '2025-11-19 23:39:51',
                'updated_at' => '2026-03-25 19:50:13',
                'deleted_at' => null
            ],
            [
                'id_user' => 45,
                'id_employee' => 'SBB-0011',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 2,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 44,
                'name' => 'Indah Yulianti',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$Ft0PBX4Kbv30KcDLn7nw6.5HvgebruUBgV1rLRjifrLkPVDRXWTFm',
                'photo' => 'default.jpg',
                'phone' => '6281412082334',
                'is_active' => 1,
                'created_at' => '2025-11-19 23:41:40',
                'updated_at' => '2025-12-22 11:51:01',
                'deleted_at' => null
            ],
            [
                'id_user' => 46,
                'id_employee' => 'KSA-0114',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 2,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 44,
                'name' => 'LEENA AMAN BHARDWAJ',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$MWPTw/GC3vIkEj1l.ozHrOKS5tDYC2hjIa2W764KhwvjeY0vO5Gy6',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-11-19 23:43:14',
                'updated_at' => '2025-11-19 23:48:14',
                'deleted_at' => null
            ],
            [
                'id_user' => 47,
                'id_employee' => 'KSA-0119',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 4,
                'id_position' => 8,
                'id_warehouse' => null,
                'supervisor' => 32,
                'name' => 'Mochamad Fahrulrozy',
                'nik' => 'NmZ0aFgzRXhqV2JhUUZGalN5RmFIZWZwcE44RElSS3VpTHZ5WWFZaDZUaz0=',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$l/SXikUp0VtDHNfPfu69sO6KfK9e6kCOSNGgLHo69oqYCr4bmgdKC',
                'photo' => 'default.jpg',
                'phone' => '6287719577130',
                'is_active' => 1,
                'created_at' => '2025-11-19 23:45:32',
                'updated_at' => '2025-12-22 11:56:27',
                'deleted_at' => null
            ],
            [
                'id_user' => 48,
                'id_employee' => 'SBB-0016',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 4,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 47,
                'name' => 'MAYA RATNASARI',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$0lFnvnQpKunQTvq9ivyirOgQ2KG8kow8pyeKlU6slRYurxu4hdDaC',
                'photo' => 'default.jpg',
                'phone' => '6285718416159',
                'is_active' => 1,
                'created_at' => '2025-11-19 23:47:08',
                'updated_at' => '2025-12-22 12:06:28',
                'deleted_at' => null
            ],
            [
                'id_user' => 49,
                'id_employee' => 'SBB-0071',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 4,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 47,
                'name' => 'Rizki Putri Ashari',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$xaYmLkJtvsVAbrJ6cXJeIuAvkSCQZBG8nFvTM3aOAn9JND.5aJYiG',
                'photo' => 'default.jpg',
                'phone' => '6285718416159',
                'is_active' => 1,
                'created_at' => '2025-12-02 12:29:42',
                'updated_at' => '2025-12-22 11:50:52',
                'deleted_at' => null
            ],
            [
                'id_user' => 50,
                'id_employee' => 'SBB-0072',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 8,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 24,
                'name' => 'Dian Anindita',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$8Rqju1UFl4MJ5z/90nxLAeDkSqUZsx/3Q1AJi6zMCCslTwC8zFmxa',
                'photo' => 'default.jpg',
                'phone' => '6285756813668',
                'is_active' => 1,
                'created_at' => '2025-12-03 12:54:45',
                'updated_at' => '2025-12-28 13:14:09',
                'deleted_at' => null
            ],
            [
                'id_user' => 51,
                'id_employee' => 'SBB-0018',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 13,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'MARIANI SIDABUTAR',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$z7aUGpZ1o00WGq7EL8gy6.pYcUDXo.8tOAoKf/g7KbdYKWYqE.vhG',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-03 12:56:30',
                'updated_at' => '2025-12-03 12:56:30',
                'deleted_at' => null
            ],
            [
                'id_user' => 52,
                'id_employee' => 'SBB-0029',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 6,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 31,
                'name' => 'Nadya Rahmawati Saepulloh',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$12$e5k1JxyGJdsU2r1xNziIDuMqQ0iz/7LmgfgumbcqGJH/oZeDMCTSO',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-03 12:58:21',
                'updated_at' => '2026-04-05 18:29:05',
                'deleted_at' => null
            ],
            [
                'id_user' => 53,
                'id_employee' => 'KSA-0118',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 7,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'Tiwi Handayani',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$GLOerzJsMpZJGXKshoeXkOxPslGXWlJ3btG04UJYWXP4nb9lskD2K',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-03 13:03:08',
                'updated_at' => '2026-03-17 14:22:20',
                'deleted_at' => null
            ],
            [
                'id_user' => 54,
                'id_employee' => 'KSA-0010A',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 3,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'KHUSNAWATI (NANA)',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$HUGIBTKIEi/iek4lsxTfne1sfT4soWExLpZi6KkUcfSW936GhD3QK',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-07 11:41:56',
                'updated_at' => '2025-12-07 14:12:19',
                'deleted_at' => null
            ],
            [
                'id_user' => 55,
                'id_employee' => 'SBB-0064A',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 6,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 31,
                'name' => 'Inggrid Febby Isnaini Sutarlan',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$iWHxFOkEBUlgkGgBdQm9Ou1I3aC28lMqux.b4e8hAE1l8dg.jUNfW',
                'photo' => 'default.jpg',
                'phone' => '6289678910546',
                'is_active' => 1,
                'created_at' => '2025-12-07 12:03:12',
                'updated_at' => '2025-12-22 12:53:53',
                'deleted_at' => null
            ],
            [
                'id_user' => 56,
                'id_employee' => 'KSA-0047',
                'id_company' => 6,
                'id_branch' => 3,
                'id_departement' => 11,
                'id_position' => 3,
                'id_warehouse' => 5,
                'supervisor' => 40,
                'name' => 'KHOIRIYAH',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$tzI0SznQkfB6qQSIASwO2uNlYeFSmNkLNncMPYl0bqR8.zy1Q56Py',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-08 14:05:40',
                'updated_at' => '2026-03-24 20:16:42',
                'deleted_at' => null
            ],
            [
                'id_user' => 57,
                'id_employee' => 'KSA-0116',
                'id_company' => 6,
                'id_branch' => 3,
                'id_departement' => 11,
                'id_position' => 3,
                'id_warehouse' => 5,
                'supervisor' => 40,
                'name' => 'SUSI LESTARI',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$LNuttncxkTo5960Ghz4hQOUAyvso57fJvZluixF6WRoZh.XGmD2fG',
                'photo' => 'default.jpg',
                'phone' => '6285602753726',
                'is_active' => 1,
                'created_at' => '2025-12-08 14:07:37',
                'updated_at' => '2026-03-24 20:19:45',
                'deleted_at' => null
            ],
            [
                'id_user' => 58,
                'id_employee' => 'KSA-0025',
                'id_company' => 6,
                'id_branch' => 4,
                'id_departement' => 6,
                'id_position' => 3,
                'id_warehouse' => 27,
                'supervisor' => 31,
                'name' => 'Usman',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$krxW04tbE6COHRZuQMXdlu9Txa2j4K1QF6rM0D5u.51M3801PJWem',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-08 14:10:09',
                'updated_at' => '2026-03-24 20:18:37',
                'deleted_at' => null
            ],
            [
                'id_user' => 59,
                'id_employee' => 'KSA-0000',
                'id_company' => 6,
                'id_branch' => 2,
                'id_departement' => 18,
                'id_position' => 2,
                'id_warehouse' => null,
                'supervisor' => 41,
                'name' => 'Anand',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$VFZ5PViSGIp.RkB.JDC5KuS7GyY9GsCbNuCIkPpb76y766KUmCMsG',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2025-12-09 15:02:59',
                'updated_at' => '2026-03-27 00:39:05',
                'deleted_at' => null
            ],
            [
                'id_user' => 60,
                'id_employee' => 'SBB-0032',
                'id_company' => 1,
                'id_branch' => 2,
                'id_departement' => 18,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 41,
                'name' => 'Victor Sitohang',
                'nik' => 'ZDF1RzN0SGNBT0QrU3BUb1FZYlhKQT09',
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$iGRUnLmc6Q/D74X4U0w6OOWx.xceOtVAoDhrLg7lbnEh2I29uewQi',
                'photo' => 'default.jpg',
                'phone' => '6281384833829',
                'is_active' => 1,
                'created_at' => '2025-12-09 15:04:32',
                'updated_at' => '2026-03-24 20:20:10',
                'deleted_at' => null
            ],
            [
                'id_user' => 61,
                'id_employee' => 'SBB-0079',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 2,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 44,
                'name' => 'Shava',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$HL.g7acui/yen24w2gBaVuOZyBRQ98OVFbgngl8jjYOoBhvJanVN.',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2026-01-08 17:30:06',
                'updated_at' => '2026-01-08 17:30:06',
                'deleted_at' => null
            ],
            [
                'id_user' => 62,
                'id_employee' => 'SBB-0070A',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 2,
                'id_position' => 7,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'FITRI INDRIYANI',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$oezY7UTEaWOhIl5iBWdV5uZQO1jh4Z21wpnpDJkA1dxHyEODkF//2',
                'photo' => 'default.jpg',
                'phone' => '6289699844788',
                'is_active' => 0,
                'created_at' => '2026-01-21 16:31:03',
                'updated_at' => '2026-03-25 19:51:16',
                'deleted_at' => null
            ],
            [
                'id_user' => 63,
                'id_employee' => 'KSA-0106A',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 12,
                'id_position' => 7,
                'id_warehouse' => null,
                'supervisor' => 63,
                'name' => 'NEELESH RAMESHCHANDRA MAHESHWARI',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$10$tpG7m554HY0N5ll8yDWBS.OuC4Tq2f.dWeCR8efP.jnaMMlOt315a',
                'photo' => 'default.jpg',
                'phone' => '628159385142',
                'is_active' => 0,
                'created_at' => '2026-01-25 19:09:55',
                'updated_at' => '2026-03-26 19:15:25',
                'deleted_at' => null
            ],
            [
                'id_user' => 64,
                'id_employee' => 'KSA-0200',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 19,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 21,
                'name' => 'Syifa Dhiya Kusuma',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$10$FZhynz4d8hNXNuXRT1k1J.j23gTztj72Qogf355VK92oZee2M6wya',
                'photo' => 'default.jpg',
                'phone' => '6282126401161',
                'is_active' => 1,
                'created_at' => '2026-02-11 19:24:29',
                'updated_at' => '2026-02-11 19:24:29',
                'deleted_at' => null
            ],
            [
                'id_user' => 65,
                'id_employee' => 'SBB-0074',
                'id_company' => 1,
                'id_branch' => 1,
                'id_departement' => 5,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 20,
                'name' => 'Irvansyah',
                'nik' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'npwp' => 'K3FlWERCenNWVEJqVEdUclg3V3RnZz09',
                'level' => 2,
                'password' => '$2y$12$o.FZQ.PX15kyTgxcWcWqleMiAPGSzOAegq7ZHXFpEs6p9iPLY42Hy',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2026-02-25 11:53:59',
                'updated_at' => '2026-04-05 18:41:23',
                'deleted_at' => null
            ],
            [
                'id_user' => 66,
                'id_employee' => 'SBB-0000A',
                'id_company' => 6,
                'id_branch' => 1,
                'id_departement' => 1,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 1,
                'name' => 'Admin Director',
                'nik' => null,
                'npwp' => null,
                'level' => 1,
                'password' => '$2y$12$GBsbQhv78CYC6nCGuoaW2ubZLfoED/rAQ8WhvmLbuhAhIusDiOl/y',
                'photo' => 'default.jpg',
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2026-03-02 16:27:48',
                'updated_at' => '2026-03-24 18:32:47',
                'deleted_at' => null
            ],
            [
                'id_user' => 67,
                'id_employee' => 'SBB-0057',
                'id_company' => 1,
                'id_branch' => null,
                'id_departement' => 6,
                'id_position' => 3,
                'id_warehouse' => 27,
                'supervisor' => 58,
                'name' => 'Zumadil',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$12$SYc7TeyMyBEXQw7WaSfNcelY/Guk7Yxh.Wsc8Zq6C9nZRP6ZK5iSa',
                'photo' => null,
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2026-03-25 17:12:20',
                'updated_at' => '2026-03-25 17:12:20',
                'deleted_at' => null
            ],
            [
                'id_user' => 68,
                'id_employee' => 'KSA-0007',
                'id_company' => 1,
                'id_branch' => null,
                'id_departement' => 7,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 53,
                'name' => 'FANNY ALIYAH NURFADILAH',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$12$ct1eMPlkj79rGp4zZR/a3.35mfwxZiWSOYGQPAycJabCGA5Z18rF.',
                'photo' => null,
                'phone' => null,
                'is_active' => 1,
                'created_at' => '2026-03-25 19:47:53',
                'updated_at' => '2026-03-25 19:48:10',
                'deleted_at' => null
            ],
            [
                'id_user' => 69,
                'id_employee' => 'KSA-0112A',
                'id_company' => 1,
                'id_branch' => null,
                'id_departement' => 3,
                'id_position' => 3,
                'id_warehouse' => null,
                'supervisor' => 22,
                'name' => 'DEVITA SIANAWATI 2',
                'nik' => null,
                'npwp' => null,
                'level' => 2,
                'password' => '$2y$12$h94pKaONVrSjdg.GDdS62eewWP79N0eSxIdmvAxn0w/tALmczps/6',
                'photo' => null,
                'phone' => '6281231654888',
                'is_active' => 1,
                'created_at' => '2026-03-30 23:31:15',
                'updated_at' => '2026-03-31 00:11:45',
                'deleted_at' => null
            ]
        ];

        // Insert in chunks to avoid packet-size limits
        foreach (array_chunk($data, 500) as $chunk) {
            DB::table('tbl_user')->insert($chunk);
        }
    }
}
