<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TblWarehouseSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        
        $payload = [
                    [
                        'id_warehouse' => 1,
                        'warehouse_name' => 'GUDANG - BAD STOCK ACEH',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 2,
                        'warehouse_name' => 'GUDANG - BAD STOCK BATANG',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 3,
                        'warehouse_name' => 'GUDANG - BAD STOCK MEDAN KIM',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 4,
                        'warehouse_name' => 'GUDANG - BAD STOCK PABRIK GLOBAL MEDAN',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 5,
                        'warehouse_name' => 'GUDANG - BATANG',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 6,
                        'warehouse_name' => 'GUDANG - CUSTOMER',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 7,
                        'warehouse_name' => 'GUDANG - CV ALFAIRUS',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 8,
                        'warehouse_name' => 'GUDANG - CV MB JAYA',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 9,
                        'warehouse_name' => 'GUDANG - CV.LAVAZA',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 10,
                        'warehouse_name' => 'GUDANG - HUSNI MEDAN KIM',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 11,
                        'warehouse_name' => 'GUDANG - INHUTANI JATIM - TRENGGALEK',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 12,
                        'warehouse_name' => 'GUDANG - INHUTANI MEDAN',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 13,
                        'warehouse_name' => 'GUDANG - INHUTANI TRENGGALEK - JATIM',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 14,
                        'warehouse_name' => 'GUDANG - INHUTANI V',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 15,
                        'warehouse_name' => 'GUDANG - INHUTANI MEDAN',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 16,
                        'warehouse_name' => 'GUDANG - MEDAN KIM',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 17,
                        'warehouse_name' => 'GUDANG - MOH.KURNIADI',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 18,
                        'warehouse_name' => 'GUDANG - PABRIK GLOBAL MEDAN',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 20,
                        'warehouse_name' => 'GUDANG - PERHUTANI JABAR',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 21,
                        'warehouse_name' => 'GUDANG - PERHUTANI JATENG',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 22,
                        'warehouse_name' => 'GUDANG - PERHUTANI JATIM',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 23,
                        'warehouse_name' => 'GUDANG - PERHUTANI SULAWESI',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 24,
                        'warehouse_name' => 'GUDANG - PINJAM KSA',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 25,
                        'warehouse_name' => 'GUDANG - PINJAM SBB',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 26,
                        'warehouse_name' => 'GUDANG - PT EMB MERKUSI CHEMICAL',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 27,
                        'warehouse_name' => 'GUDANG - PT. PMI ACEH',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 28,
                        'warehouse_name' => 'GUDANG - PT.KEFFI WANGI',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 29,
                        'warehouse_name' => 'GUDANG - SUPPLIER',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 30,
                        'warehouse_name' => 'GUDANG - UTAMA',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 31,
                        'warehouse_name' => 'GUDANG TANGKI GTO - ACEH',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 32,
                        'warehouse_name' => 'GUDANG-Jaya Media Nusantara Aceh Tengah',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 33,
                        'warehouse_name' => 'Transit (AOL System)',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'id_warehouse' => 34,
                        'warehouse_name' => 'PT. RESINA CONIFERA INDONESIA',
                        'address' => null,
                        'id_user' => 1,
                        'is_active' => 1,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
        ];

        $chunks = array_chunk($payload, 50);
        foreach ($chunks as $chunk) {
            DB::table('tbl_warehouse')->insertOrIgnore($chunk);
        }

        Schema::enableForeignKeyConstraints();
    }
}
