<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SrAttachmentSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['id_attachment_sr' => 1, 'id_sr' => 1, 'file_name' => 46, 'created_at' => 40, 'updated_at' => 'BUKTI TF ',],
            ['id_attachment_sr' => 2, 'id_sr' => 1, 'file_name' => 46, 'created_at' => 40, 'updated_at' => 'BUKTI TF ',],
            ['id_attachment_sr' => 3, 'id_sr' => 1, 'file_name' => 38, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 4, 'id_sr' => 1, 'file_name' => 38, 'created_at' => 40, 'updated_at' => 'INVOICE',],
            ['id_attachment_sr' => 5, 'id_sr' => 1, 'file_name' => 42, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 6, 'id_sr' => 1, 'file_name' => 48, 'created_at' => 40, 'updated_at' => 'PI',],
            ['id_attachment_sr' => 7, 'id_sr' => 1, 'file_name' => 42, 'created_at' => 40, 'updated_at' => 'PO ',],
            ['id_attachment_sr' => 8, 'id_sr' => 2, 'file_name' => 38, 'created_at' => 33, 'updated_at' => '',],
            ['id_attachment_sr' => 9, 'id_sr' => 2, 'file_name' => 38, 'created_at' => 33, 'updated_at' => '',],
            ['id_attachment_sr' => 10, 'id_sr' => 2, 'file_name' => 38, 'created_at' => 33, 'updated_at' => '',],
            ['id_attachment_sr' => 12, 'id_sr' => 2, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 15, 'id_sr' => 3, 'file_name' => 63, 'created_at' => 52, 'updated_at' => 'nota kasbon ',],
            ['id_attachment_sr' => 16, 'id_sr' => 1, 'file_name' => 38, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 17, 'id_sr' => 4, 'file_name' => 46, 'created_at' => 52, 'updated_at' => 'MON PENYELESAIAN',],
            ['id_attachment_sr' => 18, 'id_sr' => 4, 'file_name' => 46, 'created_at' => 52, 'updated_at' => 'MON PENYELESAIAN',],
            ['id_attachment_sr' => 19, 'id_sr' => 4, 'file_name' => 46, 'created_at' => 52, 'updated_at' => 'MON PENYELESAIAN',],
            ['id_attachment_sr' => 20, 'id_sr' => 6, 'file_name' => 40, 'created_at' => 55, 'updated_at' => 'nota kasbon ',],
            ['id_attachment_sr' => 21, 'id_sr' => 6, 'file_name' => 40, 'created_at' => 55, 'updated_at' => 'nota kasbon ',],
            ['id_attachment_sr' => 22, 'id_sr' => 7, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 23, 'id_sr' => 8, 'file_name' => 40, 'created_at' => 55, 'updated_at' => 'kwitansi',],
            ['id_attachment_sr' => 26, 'id_sr' => 9, 'file_name' => 40, 'created_at' => 52, 'updated_at' => 'kwitansi',],
            ['id_attachment_sr' => 27, 'id_sr' => 11, 'file_name' => 43, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 28, 'id_sr' => 11, 'file_name' => 41, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 29, 'id_sr' => 11, 'file_name' => 47, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 30, 'id_sr' => 11, 'file_name' => 48, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 31, 'id_sr' => 11, 'file_name' => 41, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 32, 'id_sr' => 11, 'file_name' => 43, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 33, 'id_sr' => 11, 'file_name' => 47, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 34, 'id_sr' => 11, 'file_name' => 48, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 35, 'id_sr' => 12, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 36, 'id_sr' => 12, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 37, 'id_sr' => 13, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 38, 'id_sr' => 13, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 39, 'id_sr' => 13, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 40, 'id_sr' => 13, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 42, 'id_sr' => 14, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 43, 'id_sr' => 14, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 44, 'id_sr' => 14, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 45, 'id_sr' => 14, 'file_name' => 46, 'created_at' => 46, 'updated_at' => '',],
            ['id_attachment_sr' => 46, 'id_sr' => 15, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 47, 'id_sr' => 17, 'file_name' => 43, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 48, 'id_sr' => 17, 'file_name' => 47, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 49, 'id_sr' => 17, 'file_name' => 41, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 50, 'id_sr' => 16, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'LAPORAN PEGELUARAN RESEPSIONIS SBB WEEK 1 ',],
            ['id_attachment_sr' => 51, 'id_sr' => 17, 'file_name' => 48, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 52, 'id_sr' => 17, 'file_name' => 40, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 53, 'id_sr' => 17, 'file_name' => 46, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 54, 'id_sr' => 18, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'LAPORAN PEGELUARAN RESEPSIONIS KSA WEEK 1  02-09/01/2026',],
            ['id_attachment_sr' => 55, 'id_sr' => 19, 'file_name' => 63, 'created_at' => 52, 'updated_at' => 'NOTA',],
            ['id_attachment_sr' => 56, 'id_sr' => 20, 'file_name' => 63, 'created_at' => 52, 'updated_at' => 'NOTA',],
            ['id_attachment_sr' => 57, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 58, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 59, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 60, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 61, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 62, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 63, 'id_sr' => 21, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 64, 'id_sr' => 22, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 65, 'id_sr' => 23, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'NOTA RSP SBB WEEK 2 TGL 12-21/01/2026',],
            ['id_attachment_sr' => 66, 'id_sr' => 24, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'NOTA RSP KSA WEEK 2 TGL 12-21/01/2026',],
            ['id_attachment_sr' => 67, 'id_sr' => 22, 'file_name' => 0, 'created_at' => 49, 'updated_at' => 'Invoice baru',],
            ['id_attachment_sr' => 68, 'id_sr' => 25, 'file_name' => 40, 'created_at' => 52, 'updated_at' => 'NOTA',],
            ['id_attachment_sr' => 69, 'id_sr' => 25, 'file_name' => 46, 'created_at' => 52, 'updated_at' => 'MON REALISASI',],
            ['id_attachment_sr' => 70, 'id_sr' => 26, 'file_name' => 40, 'created_at' => 52, 'updated_at' => 'kwitansi',],
            ['id_attachment_sr' => 71, 'id_sr' => 27, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 72, 'id_sr' => 27, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 73, 'id_sr' => 27, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 74, 'id_sr' => 27, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 75, 'id_sr' => 28, 'file_name' => 46, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 76, 'id_sr' => 29, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'RINCIAN PENGELUARAN OP RESEPSIONIS SBB 22/01/2026 - 03/02/2026',],
            ['id_attachment_sr' => 77, 'id_sr' => 30, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'RINCIAN PENGELUARAN OP RESEPSIONIS KSA 22/01/2026 - 03/02/2026',],
            ['id_attachment_sr' => 78, 'id_sr' => 31, 'file_name' => 38, 'created_at' => 41, 'updated_at' => 'INVOICE',],
            ['id_attachment_sr' => 79, 'id_sr' => 31, 'file_name' => 38, 'created_at' => 41, 'updated_at' => 'INVOICE',],
            ['id_attachment_sr' => 80, 'id_sr' => 31, 'file_name' => 38, 'created_at' => 41, 'updated_at' => 'INVOICE',],
            ['id_attachment_sr' => 81, 'id_sr' => 31, 'file_name' => 38, 'created_at' => 41, 'updated_at' => 'INVOICE',],
            ['id_attachment_sr' => 82, 'id_sr' => 31, 'file_name' => 46, 'created_at' => 41, 'updated_at' => 'HISTORY SALDO',],
            ['id_attachment_sr' => 83, 'id_sr' => 32, 'file_name' => 38, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 84, 'id_sr' => 32, 'file_name' => 48, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 85, 'id_sr' => 33, 'file_name' => 38, 'created_at' => 33, 'updated_at' => 'INV',],
            ['id_attachment_sr' => 86, 'id_sr' => 34, 'file_name' => 46, 'created_at' => 52, 'updated_at' => 'REALISASI PERJADIN',],
            ['id_attachment_sr' => 87, 'id_sr' => 35, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 88, 'id_sr' => 35, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 89, 'id_sr' => 35, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 90, 'id_sr' => 35, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 91, 'id_sr' => 35, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 92, 'id_sr' => 35, 'file_name' => 40, 'created_at' => 34, 'updated_at' => 'Kwitansi',],
            ['id_attachment_sr' => 93, 'id_sr' => 36, 'file_name' => 46, 'created_at' => 52, 'updated_at' => 'BUKTI TF ',],
            ['id_attachment_sr' => 94, 'id_sr' => 37, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'NOTA OP KSA 04-12 FEB 2026',],
            ['id_attachment_sr' => 95, 'id_sr' => 37, 'file_name' => 67, 'created_at' => 53, 'updated_at' => 'RINCIAN PENGGUNAAN DANA OP 04-12 FEB 2026',],
            ['id_attachment_sr' => 96, 'id_sr' => 38, 'file_name' => 63, 'created_at' => 53, 'updated_at' => 'NOTA RESEPSIONIS SBB 04-12 FEB 2026',],
            ['id_attachment_sr' => 97, 'id_sr' => 38, 'file_name' => 67, 'created_at' => 53, 'updated_at' => 'RINCIAN PENGELUARAN OP RESEPSIONIS SBB 04-12 FEB 2026',],
            ['id_attachment_sr' => 98, 'id_sr' => 39, 'file_name' => 0, 'created_at' => 26, 'updated_at' => 'INVOICE JOBSTREET',],
            ['id_attachment_sr' => 99, 'id_sr' => 39, 'file_name' => 0, 'created_at' => 26, 'updated_at' => 'BUKTI BAYAR',],
            ['id_attachment_sr' => 100, 'id_sr' => 40, 'file_name' => 46, 'created_at' => 40, 'updated_at' => '',],
            ['id_attachment_sr' => 101, 'id_sr' => 41, 'file_name' => 63, 'created_at' => 52, 'updated_at' => 'nota kasbon ',],
        ];

        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('tbl_attachment_sr')->upsert($chunk, ['id_attachment_sr'], ['id_attachment_sr', 'id_sr', 'file_name', 'created_at', 'updated_at']);
        }
    }
}
