<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SrSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['id_sr' => 1, 'id_pr' => 61, 'id_doc_type' => 3, 'id_cost_type' => 15, 'id_cost_category' => 12, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 40, 'id_departement' => 8, 'id_company' => 6, 'id_vendor' => 161, 'id_email_vendor' => null, 'id_norek_vendor' => null, 'id_email_user' => 54, 'id_warehouse' => null, 'subject' => 'PO.KSA.2512.00447', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => 'PT. KRISHNA SUKSES ABADI', 'nama_penerima' => '020800004937', 'norek' => 'submit_SR_by401', 'qr' => 11, 'status' => null, 'created_at' => '2026-01-13 03:41:08', ],
            ['id_sr' => 2, 'id_pr' => 8, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 135, 'id_email_vendor' => null, 'id_norek_vendor' => 131, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by332', 'qr' => 7, 'status' => null, 'created_at' => '2025-12-26 07:23:19', ],
            ['id_sr' => 3, 'id_pr' => 25, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 144, 'id_email_vendor' => null, 'id_norek_vendor' => 148, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by523', 'qr' => 11, 'status' => null, 'created_at' => '2026-01-05 04:48:56', ],
            ['id_sr' => 4, 'id_pr' => 31, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 150, 'id_email_vendor' => null, 'id_norek_vendor' => 155, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => 'SBB/PROD/09122025', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by524', 'qr' => 7, 'status' => null, 'created_at' => '2026-01-02 07:54:59', ],
            ['id_sr' => 6, 'id_pr' => 80, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 55, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 150, 'id_email_vendor' => null, 'id_norek_vendor' => 155, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by556', 'qr' => 11, 'status' => null, 'created_at' => '2025-12-26 07:23:42', ],
            ['id_sr' => 7, 'id_pr' => 96, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 135, 'id_email_vendor' => null, 'id_norek_vendor' => 131, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by337', 'qr' => 7, 'status' => null, 'created_at' => '2025-12-26 07:24:00', ],
            ['id_sr' => 8, 'id_pr' => 94, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 55, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 168, 'id_email_vendor' => null, 'id_norek_vendor' => null, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => 'PT. SUMBER BANYU BIRU', 'nama_penerima' => '020800020487', 'norek' => 'submit_SR_by558', 'qr' => 11, 'status' => null, 'created_at' => '2026-01-02 02:06:52', ],
            ['id_sr' => 9, 'id_pr' => 166, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 6, 'id_vendor' => 150, 'id_email_vendor' => null, 'id_norek_vendor' => 155, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by529', 'qr' => 11, 'status' => null, 'created_at' => '2025-12-29 09:26:18', ],
            ['id_sr' => 11, 'id_pr' => 104, 'id_doc_type' => 3, 'id_cost_type' => 14, 'id_cost_category' => 12, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 40, 'id_departement' => 8, 'id_company' => 1, 'id_vendor' => 45, 'id_email_vendor' => null, 'id_norek_vendor' => 45, 'id_email_user' => 54, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by4011', 'qr' => 1, 'status' => null, 'created_at' => '2025-12-26 02:54:51', ],
            ['id_sr' => 12, 'id_pr' => 196, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => '26122025', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3312', 'qr' => 5, 'status' => null, 'created_at' => '2026-01-07 03:05:53', ],
            ['id_sr' => 13, 'id_pr' => 305, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 34, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 214, 'id_email_vendor' => null, 'id_norek_vendor' => 216, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3413', 'qr' => 7, 'status' => null, 'created_at' => '2026-01-09 07:13:31', ],
            ['id_sr' => 14, 'id_pr' => 336, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 135, 'id_email_vendor' => null, 'id_norek_vendor' => 131, 'id_email_user' => 107, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3314', 'qr' => 11, 'status' => null, 'created_at' => '2026-01-09 08:28:40', ],
            ['id_sr' => 15, 'id_pr' => 359, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => 107, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3315', 'qr' => 5, 'status' => null, 'created_at' => '2026-01-19 10:13:10', ],
            ['id_sr' => 16, 'id_pr' => 297, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 1, 'id_vendor' => 205, 'id_email_vendor' => null, 'id_norek_vendor' => 207, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5316', 'qr' => 5, 'status' => null, 'created_at' => '2026-01-13 03:33:05', ],
            ['id_sr' => 17, 'id_pr' => 395, 'id_doc_type' => 3, 'id_cost_type' => 14, 'id_cost_category' => 12, 'id_branch' => 3, 'id_loan' => null, 'id_user' => 40, 'id_departement' => 8, 'id_company' => 6, 'id_vendor' => 45, 'id_email_vendor' => null, 'id_norek_vendor' => 45, 'id_email_user' => 54, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by4017', 'qr' => 5, 'status' => null, 'created_at' => '2026-01-13 03:31:05', ],
            ['id_sr' => 18, 'id_pr' => 294, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5318', 'qr' => 7, 'status' => null, 'created_at' => '2026-01-14 01:54:37', ],
            ['id_sr' => 19, 'id_pr' => 424, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 9, 'id_vendor' => 150, 'id_email_vendor' => null, 'id_norek_vendor' => 155, 'id_email_user' => 125, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5219', 'qr' => 11, 'status' => null, 'created_at' => '2026-01-22 02:51:33', ],
            ['id_sr' => 20, 'id_pr' => 415, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 168, 'id_email_vendor' => null, 'id_norek_vendor' => 174, 'id_email_user' => 125, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5220', 'qr' => 11, 'status' => null, 'created_at' => '2026-01-23 08:36:53', ],
            ['id_sr' => 21, 'id_pr' => 373, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 34, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 214, 'id_email_vendor' => null, 'id_norek_vendor' => 216, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3421', 'qr' => 7, 'status' => null, 'created_at' => '2026-01-20 02:52:34', ],
            ['id_sr' => 22, 'id_pr' => 81, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3322', 'qr' => 6, 'status' => null, 'created_at' => '2026-01-30 04:15:07', ],
            ['id_sr' => 23, 'id_pr' => 410, 'id_doc_type' => 3, 'id_cost_type' => 14, 'id_cost_category' => 12, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 1, 'id_vendor' => 205, 'id_email_vendor' => null, 'id_norek_vendor' => 207, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5323', 'qr' => 7, 'status' => null, 'created_at' => '2026-01-23 07:50:46', ],
            ['id_sr' => 24, 'id_pr' => 411, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5324', 'qr' => 10, 'status' => null, 'created_at' => '2026-01-23 07:30:27', ],
            ['id_sr' => 25, 'id_pr' => 429, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 205, 'id_email_vendor' => null, 'id_norek_vendor' => 207, 'id_email_user' => 125, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5225', 'qr' => 4, 'status' => null, 'created_at' => '2026-01-30 09:39:45', ],
            ['id_sr' => 26, 'id_pr' => 541, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 2, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 6, 'id_vendor' => 168, 'id_email_vendor' => null, 'id_norek_vendor' => 174, 'id_email_user' => 126, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5226', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-03 09:41:06', ],
            ['id_sr' => 27, 'id_pr' => 396, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 34, 'id_departement' => 17, 'id_company' => 9, 'id_vendor' => 272, 'id_email_vendor' => null, 'id_norek_vendor' => null, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => 'PT. Sumber Banyu Biru', 'nama_penerima' => '020800020487', 'norek' => 'submit_SR_by3427', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-03 06:49:54', ],
            ['id_sr' => 28, 'id_pr' => 469, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 40, 'id_departement' => 8, 'id_company' => 6, 'id_vendor' => 251, 'id_email_vendor' => null, 'id_norek_vendor' => 254, 'id_email_user' => 54, 'id_warehouse' => null, 'subject' => '19-01-2026', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => null, 'qr' => null, 'status' => null, 'created_at' => '2026-02-03 07:27:17', ],
            ['id_sr' => 29, 'id_pr' => 505, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 1, 'id_vendor' => 205, 'id_email_vendor' => null, 'id_norek_vendor' => 207, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5329', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-05 06:47:36', ],
            ['id_sr' => 30, 'id_pr' => 504, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5330', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-05 06:47:10', ],
            ['id_sr' => 31, 'id_pr' => 461, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 41, 'id_departement' => 8, 'id_company' => 1, 'id_vendor' => 205, 'id_email_vendor' => null, 'id_norek_vendor' => 207, 'id_email_user' => 124, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by4131', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-11 06:29:27', ],
            ['id_sr' => 32, 'id_pr' => 335, 'id_doc_type' => 3, 'id_cost_type' => 14, 'id_cost_category' => 12, 'id_branch' => 3, 'id_loan' => null, 'id_user' => 40, 'id_departement' => 8, 'id_company' => 6, 'id_vendor' => 115, 'id_email_vendor' => null, 'id_norek_vendor' => 113, 'id_email_user' => 54, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by4032', 'qr' => 5, 'status' => null, 'created_at' => '2026-02-11 05:58:26', ],
            ['id_sr' => 33, 'id_pr' => 605, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 33, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 135, 'id_email_vendor' => null, 'id_norek_vendor' => 131, 'id_email_user' => 107, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3333', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-10 11:59:30', ],
            ['id_sr' => 34, 'id_pr' => 613, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 2, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 6, 'id_vendor' => 168, 'id_email_vendor' => null, 'id_norek_vendor' => 174, 'id_email_user' => 126, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5234', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-09 09:12:54', ],
            ['id_sr' => 35, 'id_pr' => 641, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 34, 'id_departement' => 17, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => null, 'id_warehouse' => null, 'subject' => '0006', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by3435', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-18 04:23:20', ],
            ['id_sr' => 36, 'id_pr' => 674, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 1, 'id_vendor' => 244, 'id_email_vendor' => null, 'id_norek_vendor' => null, 'id_email_user' => 125, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => 'SUMBER BANYU BIRU', 'nama_penerima' => '020800020487', 'norek' => 'submit_SR_by5236', 'qr' => 6, 'status' => null, 'created_at' => '2026-02-13 08:31:48', ],
            ['id_sr' => 37, 'id_pr' => 651, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => '19/KSA-HR/INV//2026', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5337', 'qr' => 5, 'status' => null, 'created_at' => '2026-02-18 04:50:41', ],
            ['id_sr' => 38, 'id_pr' => 650, 'id_doc_type' => 3, 'id_cost_type' => 17, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 53, 'id_departement' => 7, 'id_company' => 1, 'id_vendor' => 205, 'id_email_vendor' => null, 'id_norek_vendor' => 207, 'id_email_user' => 78, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by5338', 'qr' => 5, 'status' => null, 'created_at' => '2026-02-16 06:14:06', ],
            ['id_sr' => 39, 'id_pr' => 770, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 1, 'id_loan' => null, 'id_user' => 26, 'id_departement' => 7, 'id_company' => 6, 'id_vendor' => 206, 'id_email_vendor' => null, 'id_norek_vendor' => 208, 'id_email_user' => 40, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => 'submit_SR_by2639', 'qr' => 3, 'status' => null, 'created_at' => '2026-02-12 07:52:14', ],
            ['id_sr' => 40, 'id_pr' => 790, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 4, 'id_loan' => null, 'id_user' => 40, 'id_departement' => 8, 'id_company' => 1, 'id_vendor' => 117, 'id_email_vendor' => null, 'id_norek_vendor' => 115, 'id_email_user' => 54, 'id_warehouse' => null, 'subject' => '11-02-2026', 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => '', 'nama_penerima' => '', 'norek' => null, 'qr' => null, 'status' => null, 'created_at' => '2026-02-16 07:34:26', ],
            ['id_sr' => 41, 'id_pr' => 720, 'id_doc_type' => 3, 'id_cost_type' => 16, 'id_cost_category' => 10, 'id_branch' => 2, 'id_loan' => null, 'id_user' => 52, 'id_departement' => 6, 'id_company' => 6, 'id_vendor' => 168, 'id_email_vendor' => null, 'id_norek_vendor' => null, 'id_email_user' => 125, 'id_warehouse' => null, 'subject' => null, 'no_invoice' => 0.0, 'additional_discount' => 1, 'payment_method' => null, 'nama_bank' => 'PT. KRISHNA SUKSES ABADI', 'nama_penerima' => '020800004937', 'norek' => 'submit_SR_by5241', 'qr' => 1, 'status' => null, 'created_at' => '2026-02-18 09:12:14', ],
        ];

        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('tbl_sr')->upsert($chunk, ['id_sr'], ['id_sr', 'id_pr', 'id_doc_type', 'id_cost_type', 'id_cost_category', 'id_branch', 'id_loan', 'id_user', 'id_departement', 'id_company', 'id_vendor', 'id_email_vendor', 'id_norek_vendor', 'id_email_user', 'id_warehouse', 'subject', 'no_invoice', 'additional_discount', 'payment_method', 'nama_bank', 'nama_penerima', 'norek', 'qr', 'status', 'created_at', 'updated_at', 'deleted_at']);
        }
    }
}
